// Original semantic tasks verified against chapter 3; no morphology-only filler.
import {chapter as originalChapter} from './certification-bank.js';
const one=(id,target,prompt,options,explanation)=>({id,target,type:'single',prompt,options:options.map((text,i)=>({id:`${id}-${i}`,text})),correct:[`${id}-0`],explanation});
const many=(id,target,prompt,options,indices,explanation)=>({id,target,type:'multi',prompt,options:options.map((text,i)=>({id:`${id}-${i}`,text})),correct:indices.map(i=>`${id}-${i}`),explanation});
export const chapterV2={...originalChapter,bankVersion:'comprehension-lab-v2'};
export const bankV2=[
many('v2-am1','amphibian','选出两句中 amphibian 与后面的解释相符的用法。',['The amphibian taxied off the slipway and headed for the runway. → 水陆两用飞机','The researchers returned the amphibian to the breeding pond. → 两栖动物','The amphibian was fitted with floats before its first flight. → 水生植物','The amphibian population declined after the ponds dried. → 一队水陆两用车辆'],[0,1],'runway、flight 支持飞机义；population 与 breeding pond 的生态语境支持动物义。不能仅凭有水就统一译为动物。'),
one('v2-am2','amphibian','The museum moved its amphibian from the hangar to a pond, where visitors watched it taxi.\n结合场景，最稳妥的理解是哪项？',['展示的是能在水面滑行的飞机','展示的是两栖动物在水中觅食','展示的是只供水上运行的普通船','展示的是一种水生植物的移动展览'],'hangar 与 taxi 支持航空器义。pond 不能单独推翻这些线索；amphibian 同时强调可水陆运行。'),
many('v2-aq','aquatic','选出两项准确解释：\nThe tank held aquatics from the lagoon. Aquatics returned to the school timetable after water tests.',['前一句 aquatics 指水生动植物','前一句 aquatics 指一系列水上运动','后一句 aquatics 指水上运动课程','后一句 aquatics 指养殖的水生动植物'],[0,2],'同一复数形式有两个本章义项：tank held 是生物，school timetable 是体育活动。不是仅检查复数形式。'),
many('v2-can1','canopy','下列 canopy 的具体解释，哪两项成立？',['The damaged parachute canopy was spread on the hangar floor. → 降落伞伞衣','She studied the stone canopy above the niche. → 建筑龛上方的檐盖','The pilot cleaned the canopy before take-off. → 机翼表面','A pale canopy of cloud covered the valley. → 河谷中的树冠层'],[0,1],'伞衣与檐盖是独立义项；飞机 canopy 为驾驶舱透明舱盖，云层 canopy 为像罩篷一样覆盖的天空。'),
one('v2-can2','canopy','They replaced the aircraft canopy but left the parachute canopy untouched.\n哪种维修记录没有改变所指对象？',['换了驾驶舱透明舱盖，没更换伞衣','换了伞衣，没更换驾驶舱透明舱盖','换了机舱内饰，没更换降落伞背带','换了飞机外部罩篷，没修复树冠层'],'aircraft 与 parachute 分别限定透明舱盖与伞衣，不是泛指飞机覆盖物或降落伞部件。'),
many('v2-comp1','compost','按本章义项，选出两项恰当的解释。',['The nursery ordered peat-free compost for its trays. → 混合栽培土','They composted the exhausted soil. → 给土壤施堆肥','They composted the clean stems behind the shed. → 在茎秆上施堆肥','The pamphlet was a compost of promises and omissions. → 一份仅讲化肥的说明'],[0,1],'nursery/trays 支持栽培土；以土壤为宾语可以指施堆肥。clean stems 指制成堆肥；pamphlet 的少见比喻义指各种成分混成的一团。'),
one('v2-comp2','compost','We composted the leaves; later, we composted the poor soil.\n两次工作分别是什么？',['先把叶片制成堆肥，再给贫瘠土壤施堆肥','先给叶片施堆肥，再把土壤制成堆肥','两次都只把对象扔进混合垃圾箱','两次都为对象更换盆栽用的全部土壤'],'同一个动词有不同处理方向，宾语区分制肥原料与接受堆肥的土壤；词性相同仍需理解义项。'),
many('v2-cons1','consultation','选出两项正确的具体理解。',['The documents are available for consultation. → 可供查阅','The surgeon requested a consultation with two specialists about one patient. → 医生共同讨论病情','The council issued the plan after consultation with residents. → 在居民取得最终决定权后','She booked a private consultation with a lawyer. → 私下查阅律师的藏书'],[0,1],'查阅资料、共同会诊成立。与居民磋商不等于授予最终决定权；与律师的一次 consultation 是咨询而非查阅书籍。'),
one('v2-cons2','consultation','Consultation of the records preceded consultation with the families.\n哪种转述保留两种不同的活动？',['先查阅记录，再与家庭磋商','先与记录员会诊，再查阅各家的记录','先公开听证，再安排家庭医疗会诊','先由各家协商，再咨询档案馆法律顾问'],'of the records 为查阅资料，with the families 为磋商；不要把对象与活动擅自换掉。'),
one('v2-det','deteriorate','The relations deteriorated although the water quality improved.\n哪项最准确说明报告？',['人际或组织关系变差，水质却改善了','关系与水质都变差，但速度不同','关系得到修复，水质仍在变差','关系停滞不变，水质检测尚无结论'],'deteriorate 可指关系恶化，不局限物品损坏；although 的两方面变化方向相反。'),
many('v2-down','downstream','一条河在村庄以北转弯；工厂在转弯前，采样点 downstream of the factory。哪些判断有根据？',['沿水流从工厂继续前行可以到采样点','采样点必定在地图的更南面','采样点水流经过工厂所在位置','采样点必定已经进入海水区域'],[0,2],'downstream 按实际水流而非地图南北定位。相对位置不等于入海、干净或污染来源的充分证明。'),
many('v2-est','estuary','哪些描述符合本章 estuary / estuarine 的意思？选两项。',['A broad tidal reach at the river’s meeting with the sea. → 河口湾','Fish adapted to estuarine conditions. → 适应河口环境','A freshwater lake beside a large river, with no sea connection. → 必然是 estuary','A coastal pool behind a sandbar. → 与 estuary 完全同义'],[0,1],'河流入海与潮汐是河口湾线索；河旁淡水小湖可涉及 lagoon 义，沙洲后水域也不能与 estuary 简单等同。'),
many('v2-inv1','invasive','以下哪些使用了本章 invasive 的实际义项？选两项。',['She refused invasive questions about her family. → 侵犯私人领域的问题','The test was invasive because an instrument entered the body. → 侵入式医疗操作','The imported seed was invasive merely because it came from abroad. → 外来来源本身足以证明侵入性','The interviewer was invasive because she entered the interview room. → 普通进入房间'],[0,1],'隐私侵扰与侵入式医疗成立；外来不等于迅速失控扩散，普通进入房间也不自动构成这些义项。'),
one('v2-inv2','invasive','An invasive species was removed, but invasive questions continued at the meeting.\n最准确的区别是哪项？',['前者是扩散难控制的生物，后者是侵犯私人领域的问题','前者是所有外来生物，后者是来自外地的问题','前者与后者都必须涉及医疗器械进入身体','前者是本地物种，后者是未经允许进入会场的人'],'语境区分生态与隐私义；invasive 不单由地理来源或普通进入决定。'),
many('v2-lag1','lagoon','哪些水域可以用本章的 lagoon 义描述？选两项。',['人工建造，用于暂存暴雨径流的池','大河旁的小型淡水湖','所有受潮汐影响的河流入海处','任何供小船通行的航运路线'],[0,1],'本章还包括工程池与河旁小型淡水湖，不能把 lagoon 限制为咸水海岸地形；入海处偏 estuary，路线偏 waterway。'),
one('v2-lag2','lagoon','The engineer compared a stormwater lagoon with the lagoon inside an atoll.\n哪种解释保留两处区别？',['前者是人工径流池，后者是环礁内水域','前者是河口湾，后者是任何小型淡水湖','前者是天然海岸泻湖，后者是人工污水池','前者是人工航道，后者是河边草甸'],'stormwater 与 engineer 支持工程池；inside an atoll 对应环礁内部水域。'),
many('v2-mit1','mitigate','关于 mitigate / mitigation，哪些解释成立？选两项。',['Barriers mitigated the losses. → 有损失仍与句意相容','The lawyer spoke in mitigation. → 陈述可减轻过错的情节','The damage was mitigable. → 损害已在事实上彻底消失','Her attitude was mitigated. → 她的态度必然变得更严厉'],[0,1],'减轻不等于彻底消除；法庭 mitigation 是减责情节。mitigable 是可以减轻，不保证已消失；mitigate 态度可指缓和。'),
one('v2-mit2','mitigate','The defences mitigated the impact but did not prevent the flood.\n哪种转述最精确？',['洪水发生了，防护减轻了影响','洪水被完全挡住，只剩轻微风险','防护未能起任何作用，影响不变','洪水是否发生尚未知，只知道影响会较轻'],'已发生与已减轻并存；mitigate impact 不是 prevent flood，也不是完全无效。'),
many('v2-sp','species','按本章含标签的义项，选出两项准确解释。',['A species of confidence was evident. → 一类或一种确信','The Eucharistic species were discussed. → 圣餐面饼与酒的可见形态','The legal text used species for the form given to metal. → 金属的生物物种','A species within the genus was defined. → 属之上的更大逻辑分类'],[0,1],'species 包括一类事物及宗教专门义；旧法律材料的 species 为赋予的形式，逻辑 species 是属之下的种，不是上位属。'),
one('v2-trib','tributary','The tributary enters the river before the river reaches the village. The village lies upstream of the sea.\n哪种关系图正确？',['支流汇入点 → 村庄 → 入海处，按干流水向排列','村庄 → 支流汇入点 → 入海处，按干流水向排列','入海处 → 村庄 → 支流汇入点，按干流水向排列','支流必须在村庄才与干流汇合'],'tributary enters 为支流汇入；before the river reaches village 限定汇流点在村庄上游，村庄又在海的上游。'),
many('v2-prop','proposal','哪些转述恰当？选两项。',['His proposal to her concerned marriage. → 他向她求婚','The restoration proposal was approved. → 恢复建议被批准，但句子未说已完工','The proposal was detailed. → 计划已得到批准','The council discussed the proposal. → 讨论内容必然是向某人求婚'],[0,1],'proposal 包含求婚及建议；详细、讨论、批准与实际完工是不同状态。不能仅凭 proposal 自行增加事实。'),
many('v2-rec1','reclaim','选出两项符合本章 reclaim 实际义项的解释。',['The sea reclaimed the abandoned fields. → 自然重新吞没原人类用地','Workers reclaimed metal from discarded equipment. → 回收废物中的有用材料','She reclaimed the overpaid tax. → 她为未来税款作了担保','The company reclaimed land from the sea. → 海水重新淹没公司的土地'],[0,1],'主语与对象区分自然取回、人为回收及开垦；退还已付税款不是未来担保，人为填海也不是海水吞没。'),
one('v2-rec2','reclaim','The sea reclaimed land that engineers had once reclaimed.\n两处 reclaim 的方向如何不同？',['海重新吞没工程师以前开垦出的土地','海再次帮助工程师把土地变成可用地','工程师收回税款，海水使其退款失败','海与工程师都只在回收废金属'],'第一处自然重新吞没人类用地，第二处工程改造水下土地；同形、同词性也可能方向不同。'),
many('v2-rehab','rehabilitate','哪些 rehabilitate 的使用和解释相符？选两项。',['The inquiry rehabilitated her reputation. → 恢复声誉','They rehabilitated the old pump house. → 修复建筑','Therapy rehabilitated her injured hand. → 公开更正手部的声誉','The rehabilitation of former prisoners. → 把监狱楼本身重新装修'],[0,1],'恢复声誉、修复建筑、伤后康复与帮助出狱者重返生活是不同义项；不能用一个常见译法套全部对象。'),
one('v2-veg1','vegetation','After retirement he feared a life of vegetation; the marsh’s vegetation meanwhile recovered.\n两处分别指什么？',['人的单调无所事事生活；湿地的植被','人的种植劳动；湿地的人工肥料','人的康复治疗；湿地水道的修复','人的生物分类；湿地植物的种子'],'a life of vegetation 为本章比喻义，不是植物种植职业；marsh’s vegetation 为植被集合。'),
many('v2-veg2','vegetation','选出两项准确理解。',['Warmth accelerated vegetation on the bare soil. → 加快植物生长过程','A vegetational survey distinguished planted and self-sown growth. → 植被调查','She escaped a life of vegetation by taking up rowing. → 她从种植园工作改行去划船','The bank’s vegetation was removed. → 该处所有植物生长的时间被删除'],[0,1],'vegetation 可指过程，也可指植被集合或单调生活，必须用场景区分；调查涉及植被而非词形检测。'),
many('v2-way','waterway','哪两项具体解释成立？',['The skiff followed the waterway to the estuary. → 船只通行的水道','She replaced a rotted waterway along the deck’s edge. → 舷侧排水厚木板','The cargo came by waterway rather than by road. → 船上被更换的木板','The channel became a navigable waterway. → 无法让船通行的排水沟'],[0,1],'本章 waterway 包括可航行水道、水路路线和船舷排水木板；不能统一指河流或任何排水沟。'),
many('v2-ord','ordinance','根据本章相应标签，哪两项解释成立？',['A municipal ordinance limited discharges. → 地方条例','The book’s ordinance guided the reader from evidence to conclusions. → 作品的整体布局','The congregation observed an ordinance. → 必然是关于污水的地方条例','The council issued an ordinance. → 必然是一次宗教仪式'],[0,1],'ordinance 的地方条例、宗教仪式、作品布局义受对象与标签限制，不能把一个常见义当全场景通用。'),
many('v2-mun','municipality','哪两项转述保留 municipality 的所指？',['The municipality covers three villages. → 自治地区辖域包含三个村','The municipality issued the notice. → 市政当局发出通知','The municipality covers three villages. → 三个村的居民都参加了同一次会议','The municipality issued the notice. → 通知必然由全体居民投票通过'],[0,1],'municipality 可指地区或管理机构，covers 与 issued 帮助区分；不自行补造会议或全体表决。')
];
