import {safe,text} from './objective.js';import {sha256} from './practice-media.js';import {speakingEnvironment} from './private-assets.js';import {contractSnapshot,contractVersion} from '../../scripts/lib/speaking/collect.mjs';import {enqueueSupplement} from '../speaking/control.mjs';
const json=(v,s=200)=>Response.json(v,{status:s,headers:{'cache-control':'no-store'}}),limit=20*1024*1024;
export async function speakingView(db,setId){const {results}=await db.prepare('SELECT a.id,a.question_id AS questionId,a.status,a.submitted_at AS submittedAt,a.feedback_key,a.original_audio_key FROM speaking_attempts a JOIN practice_questions q ON q.id=a.question_id WHERE q.set_id=? ORDER BY a.submitted_at DESC').bind(setId).all();return results.map(({feedback_key,original_audio_key,...row})=>({...row,audioUrl:`/api/practice/speaking/attempts/${row.id}/audio`,hasFeedback:!!feedback_key}));}
function wavSeconds(bytes){const d=new DataView(bytes);if(bytes.byteLength<44||new TextDecoder().decode(bytes.slice(0,4))!=='RIFF'||new TextDecoder().decode(bytes.slice(8,12))!=='WAVE')throw Error('需要可解码 WAV');let offset=12,rate=0,size=0;while(offset+8<=bytes.byteLength){const id=new TextDecoder().decode(bytes.slice(offset,offset+4)),n=d.getUint32(offset+4,true);if(offset+8+n>bytes.byteLength)throw Error('WAV 区块截断');if(id==='fmt '){if(n<16||d.getUint16(offset+8,true)!==1||d.getUint16(offset+10,true)!==1||d.getUint32(offset+12,true)!==16000||d.getUint16(offset+22,true)!==16)throw Error('导出应为 16 kHz 单声道 PCM16');rate=d.getUint32(offset+16,true);}if(id==='data')size+=n;offset+=8+n+(n%2);}const seconds=size/rate;if(!Number.isFinite(seconds)||seconds<=0||seconds>600)throw Error('录音时长无效，最多十分钟');return seconds;}
export async function speakingRoute(request,rawEnv,{session,sameOrigin,isPublisher}){
 const path=new URL(request.url).pathname;if(!path.includes('/speaking/'))return null;const env=speakingEnvironment(rawEnv),db=env.PRACTICE_DB,bucket=env.SPEAKING_ASSETS;
 const upload=path.match(/^\/api\/practice\/questions\/([A-Za-z0-9._:-]+)\/speaking\/audio$/);
 if(upload&&request.method==='PUT'){
  if(!session||!sameOrigin)return json({error:'来源不允许'},403);const id=new URL(request.url).searchParams.get('id'),mime=request.headers.get('content-type')?.split(';')[0];if(!safe(id)||!['audio/mp4','audio/m4a','audio/x-m4a','audio/webm','audio/wav','audio/x-wav','audio/mpeg','audio/aac','audio/ogg'].includes(mime)||Number(request.headers.get('content-length'))>limit)return json({error:'录音格式或大小无效，最大 20 MiB'},400);
  const q=await db.prepare('SELECT * FROM practice_questions WHERE id=? AND kind=\'speaking\'').bind(upload[1]).first();if(!q)return json({error:'口语题不存在'},404);const bytes=await request.arrayBuffer();if(bytes.byteLength<100||bytes.byteLength>limit)return json({error:'录音大小无效'},400);const digest=await sha256(bytes),existing=await db.prepare('SELECT * FROM speaking_attempts WHERE id=?').bind(id).first();if(existing){if(existing.original_digest!==digest||existing.question_id!==q.id)return json({error:'答卷版本已固定'},409);return json({id,status:existing.status,reused:true});}
  const prefix=`speaking/${id}`,key=`${prefix}/original/${digest}`,snapshotKey=`${prefix}/question.json`,reveal=await db.prepare('SELECT 1 FROM practice_reveals WHERE question_id=?').bind(q.id).first(),promptSeen=await db.prepare('SELECT 1 FROM practice_prompt_reveals WHERE question_id=?').bind(q.id).first();await bucket.put(key,bytes,{httpMetadata:{contentType:mime}});await bucket.put(snapshotKey,JSON.stringify({...q,originalMime:mime,promptSeenBefore:!!promptSeen}),{httpMetadata:{contentType:'application/json'}});await db.prepare("INSERT INTO speaking_attempts(id,question_id,question_snapshot_key,original_audio_key,original_digest,reference_seen_before,status,submitted_at) VALUES(?,?,?,?,?,?,'preparing',?)").bind(id,q.id,snapshotKey,key,digest,reveal?1:0,Date.now()).run();return json({id,status:'preparing'},201);
 }
 const attempt=path.match(/^\/api\/practice\/speaking\/attempts\/([A-Za-z0-9._:-]+)\/(audio|feedback)$/);
 if(attempt&&['GET','HEAD'].includes(request.method)){const row=await db.prepare('SELECT * FROM speaking_attempts WHERE id=?').bind(attempt[1]).first();if(!row)return json({error:'答卷不存在'},404);if(attempt[2]==='feedback'){if(!row.feedback_key)return json({status:row.status,feedback:null});return json({status:row.status,feedback:await (await bucket.get(row.feedback_key)).json()});}const audio=await bucket.get(row.original_audio_key),snapshot=await bucket.get(row.question_snapshot_key);if(!audio)return json({error:'录音暂不可用'},503);const bytes=await audio.arrayBuffer(),mime=(await snapshot.json()).originalMime,n=bytes.byteLength,headers={'content-type':mime,'cache-control':'private, no-store','content-length':String(n),'accept-ranges':'bytes','x-content-type-options':'nosniff'},range=request.headers.get('range');if(range){const m=range.match(/^bytes=(\d*)-(\d*)$/);if(!m||(!m[1]&&!m[2]))return new Response(null,{status:416,headers:{'content-range':`bytes */${n}`}});const start=m[1]?Number(m[1]):Math.max(0,n-Number(m[2])),end=m[1]?(m[2]?Math.min(n-1,Number(m[2])):n-1):n-1;if(start>=n||start>end)return new Response(null,{status:416,headers:{'content-range':`bytes */${n}`}});return new Response(request.method==='HEAD'?null:bytes.slice(start,end+1),{status:206,headers:{...headers,'content-range':`bytes ${start}-${end}/${n}`,'content-length':String(end-start+1)}});}return new Response(request.method==='HEAD'?null:bytes,{headers});}
 if(!path.startsWith('/api/practice/publisher/speaking/'))return null;if(!isPublisher)return json({error:'发布身份无效'},401);
 if(path.endsWith('/next')&&request.method==='GET'){const at=Date.now(),preparing=await db.prepare("SELECT id FROM speaking_attempts WHERE status='preparing' ORDER BY submitted_at LIMIT 1").first(),ready=await db.prepare("SELECT id FROM speaking_attempts WHERE status='ready' OR (status='reviewing' AND claim_at<?) ORDER BY submitted_at LIMIT 1").bind(at-7200000).first(),attention=await db.prepare("SELECT id FROM speaking_attempts WHERE status='needs_attention' ORDER BY submitted_at LIMIT 1").first();return json({prepareId:preparing?.id||null,attemptId:ready?.id||null,attentionId:attention?.id||null});}
 const inspect=path.match(/^\/api\/practice\/publisher\/speaking\/([A-Za-z0-9._:-]+)\/status$/);
 if(inspect&&request.method==='GET'){const row=await db.prepare('SELECT * FROM speaking_attempts WHERE id=?').bind(inspect[1]).first();if(!row)return json({error:'答卷不存在'},404);const {results:jobs}=await db.prepare('SELECT * FROM speaking_jobs WHERE attempt_id=? ORDER BY created_at').bind(row.id).all();return json({attempt:row,jobs,manifestKeys:jobs.map(j=>`speaking/${row.id}/jobs/${j.id}/manifest.json`)});}
 const prepare=path.match(/^\/api\/practice\/publisher\/speaking\/([A-Za-z0-9._:-]+)\/prepare$/);
 if(prepare&&request.method==='PUT'){
  const row=await db.prepare('SELECT * FROM speaking_attempts WHERE id=?').bind(prepare[1]).first();if(!row)return json({error:'答卷不存在'},404);const existing=await db.prepare('SELECT id FROM speaking_jobs WHERE attempt_id=? AND parent_job_id IS NULL LIMIT 1').bind(row.id).first();if(existing)return json({id:row.id,jobId:existing.id,reused:true});if(row.status!=='preparing')return json({error:'答卷状态不允许转换'},409);const bytes=await request.arrayBuffer();if(bytes.byteLength>limit)return json({error:'WAV 超过存储上限'},400);let seconds;try{seconds=wavSeconds(bytes);}catch(e){return json({error:e.message},400);}const digest=await sha256(bytes),jobId=crypto.randomUUID(),prefix=`speaking/${row.id}/jobs/${jobId}`,audioKey=`${prefix}/audio/${digest}.wav`,snapshot=new TextEncoder().encode(JSON.stringify(contractSnapshot())),contractDigest=await sha256(snapshot),contractKey=`${prefix}/contract/${contractDigest}.json`;await bucket.put(audioKey,bytes,{httpMetadata:{contentType:'audio/wav'}});await bucket.put(contractKey,snapshot,{httpMetadata:{contentType:'application/json'}});const at=Date.now();await db.batch([db.prepare("INSERT OR IGNORE INTO speaking_jobs(id,attempt_id,contract_version,contract_digest,contract_key,audio_key,audio_digest,audio_seconds,audio_format,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'wav','queued',?,?)").bind(jobId,row.id,contractVersion,contractDigest,contractKey,audioKey,digest,seconds,at,at),db.prepare("UPDATE speaking_attempts SET status='collecting' WHERE id=? AND status='preparing'").bind(row.id)]);const winner=await db.prepare('SELECT id FROM speaking_jobs WHERE attempt_id=? AND parent_job_id IS NULL').bind(row.id).first();return json({id:row.id,jobId:winner.id,status:'collecting',seconds,reused:winner.id!==jobId});
 }
 if(path.endsWith('/asset')&&request.method==='GET'){const key=new URL(request.url).searchParams.get('key');if(!key?.startsWith('speaking/')||key.includes('..'))return json({error:'资产路径无效'},400);const file=await bucket.get(key);return file?new Response(await file.arrayBuffer(),{headers:{'cache-control':'private, no-store'}}):json({error:'资产暂不可用'},503);}
 if(path.endsWith('/details')&&request.method==='POST'){try{return json(await enqueueSupplement(env,await request.json()));}catch(e){return json({error:e.message},400);}}
 if(path.endsWith('/claim')&&request.method==='POST'){
  const at=Date.now(),row=await db.prepare("SELECT * FROM speaking_attempts WHERE status='ready' OR (status='reviewing' AND claim_at<?) ORDER BY submitted_at LIMIT 1").bind(at-7200000).first();if(!row)return json({attempt:null});const token=crypto.randomUUID(),changed=await db.prepare("UPDATE speaking_attempts SET status='reviewing',claim_token=?,claim_at=? WHERE id=? AND (status='ready' OR (status='reviewing' AND claim_at<?))").bind(token,at,row.id,at-7200000).run();if(!changed.meta.changes)return json({attempt:null});const {results:jobs}=await db.prepare('SELECT * FROM speaking_jobs WHERE attempt_id=? ORDER BY created_at,rowid').bind(row.id).all(),job=jobs.at(-1),manifest=await bucket.get(`speaking/${row.id}/jobs/${job.id}/manifest.json`);const {results:calls}=await db.prepare('SELECT * FROM speaking_calls WHERE job_id IN (SELECT id FROM speaking_jobs WHERE attempt_id=?) ORDER BY created_at,rowid').bind(row.id).all();return json({claimToken:token,attempt:{id:row.id,question:await(await bucket.get(row.question_snapshot_key)).json(),referenceSeenBefore:!!row.reference_seen_before,originalDigest:row.original_digest,originalAudioKey:row.original_audio_key,jobs,calls,manifest:manifest?await manifest.json():null}});
 }
 if(path.endsWith('/complete')&&request.method==='POST'){
  const b=await request.json();if(!safe(b.id)||!safe(b.claimToken)||!safe(b.jobId)||!text(b.feedback?.summary,3000)||!Array.isArray(b.feedback?.priorities)||b.feedback.priorities.some(x=>!text(x,1500))||!text(b.feedback?.nextStep,3000)||!text(b.feedback?.qualityScope,200)||JSON.stringify(b.feedback).length>50000)return json({error:'反馈需要完整分析、证据范围和重答建议'},400);const row=await db.prepare('SELECT * FROM speaking_attempts WHERE id=?').bind(b.id).first();if(row?.status==='reviewed')return json({ok:true,reused:true});if(!row||row.status!=='reviewing'||row.claim_token!==b.claimToken)return json({error:'领取身份无效'},409);const job=await db.prepare('SELECT 1 FROM speaking_jobs WHERE id=? AND attempt_id=?').bind(b.jobId,b.id).first();if(!job)return json({error:'采集任务不对应'},400);const key=`speaking/${b.id}/feedback/${crypto.randomUUID()}.json`;await bucket.put(key,JSON.stringify(b.feedback),{httpMetadata:{contentType:'application/json'}});await db.batch([db.prepare('INSERT INTO speaking_feedback(id,attempt_id,job_id,feedback_key,quality_scope,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),b.id,b.jobId,key,b.feedback.qualityScope,Date.now()),db.prepare("UPDATE speaking_attempts SET status='reviewed',feedback_key=?,reviewed_at=?,claim_token=NULL,claim_at=NULL WHERE id=? AND claim_token=?").bind(key,Date.now(),b.id,b.claimToken)]);return json({ok:true});
 }
 return json({error:'口语接口不存在'},404);
}
