const $=id=>document.getElementById(id),storageKey='tsl-question-voices-20261004';
const empty=()=>({sessionId:crypto.randomUUID(),voices:['a','b','c'].map(id=>({id,ratings:{naturalness:null,clarity:null,examiner:null,faithfulness:null},qualified:null,notes:''})),preferred:null,listened:[],identitiesRevealed:false});
let state;try{state=JSON.parse(localStorage.getItem(storageKey))||empty();}catch{state=empty();}
let manifest,sampleId='personal',playing=null,playingButton=null,pendingSubmission=null;
const persist=()=>{pendingSubmission=null;try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}};
const note=text=>{$('status').textContent=text;};
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options});const b=await r.json();if(!r.ok)throw Error(b.error||'请求失败，请重试');return b;}
const element=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
function stop(){if(playing){playing.pause();playing.removeAttribute('src');playing.load();playing=null;}if(playingButton){playingButton.textContent='播放题目';playingButton=null;}}
function chooseSample(id){stop();sampleId=id;$('questionText').open=false;const s=manifest.samples.find(s=>s.id===id);$('part').textContent=s.part+' · 三种声音读相同原文';$('transcript').textContent=s.text;$('taskCard').hidden=!s.card;$('taskCard').textContent=s.card||'';for(const b of $('samples').children)b.setAttribute('aria-pressed',String(b.dataset.id===id));for(const b of document.querySelectorAll('[data-play]')){b.disabled=!manifest.available.find(x=>x.id===`${b.dataset.play}-${id}`)?.ready;b.textContent=b.disabled?'音频未就绪':'播放题目';}}
function choices(options,value,onChange){const row=element('div','choice-row');for(const [id,text]of options){const b=element('button','',text);b.type='button';b.setAttribute('aria-pressed',String(id===value));b.onclick=()=>{for(const x of row.children)x.setAttribute('aria-pressed',String(x===b));onChange(id);persist();};row.append(b);}return row;}
function card(v){const data=state.voices.find(x=>x.id===v.id),card=element('section','voice-card'),head=element('div','voice-head'),play=element('button','bevel','播放题目');play.type='button';play.dataset.play=v.id;head.append(element('h2','',v.label),play);card.append(head);const info=element('p','audio-note','可在上方切换题目，听完后给这款声音评分。');card.append(info);
 play.onclick=async()=>{if(playingButton===play){stop();info.textContent='已暂停，可以重新播放。';return;}stop();const id=`${v.id}-${sampleId}`;playing=new Audio(`/api/audio/${id}`);playingButton=play;play.textContent='暂停播放';const current=playing;current.onended=()=>{if(!state.listened.includes(id)){state.listened.push(id);persist();}if(playing===current)stop();info.textContent='这段已听完，可切换题目或评分。';};current.onerror=()=>{if(playing===current)stop();info.textContent='播放未成功，请再点一次；也可尝试在 Safari 打开。';};try{await current.play();info.textContent='正在播放 · '+manifest.samples.find(s=>s.id===sampleId).title;}catch{if(playing===current)stop();info.textContent='请再点一次播放，或检查静音与音量。';}};
 for(const [key,label]of [['naturalness','自然度'],['clarity','清晰度'],['examiner','考官语气'],['faithfulness','题文忠实']]){const row=element('div','rating-row');row.append(element('span','label',label));const scores=element('div','score');scores.setAttribute('role','group');scores.setAttribute('aria-label',`${v.label} ${label}`);for(let i=1;i<=5;i++){const b=element('button','',String(i));b.type='button';b.setAttribute('aria-label',`${label} ${i} 分`);b.setAttribute('aria-pressed',String(data.ratings[key]===i));b.onclick=()=>{data.ratings[key]=i;for(const x of scores.children)x.setAttribute('aria-pressed',String(x===b));persist();note('评分已暂存，还需点击“保存评分”提交。');};scores.append(b);}row.append(scores);card.append(row);}
 const q=element('div','qualification');q.append(element('p','','你认为可以用于正式口语练习吗？'),choices([[true,'可以'],[false,'不合格']],data.qualified,value=>{data.qualified=value;}));card.append(q);const notes=element('textarea','notes');notes.maxLength=2000;notes.rows=2;notes.placeholder='可选备注：哪里机械、读错、太慢或特别自然…';notes.setAttribute('aria-label',v.label+' 备注');notes.value=data.notes;notes.oninput=()=>{data.notes=notes.value;persist();};card.append(notes);return card;
}
async function reveal(){try{const r=await api('/api/identities');$('identities').replaceChildren(...r.voices.map(v=>element('p','',`${v.label}：${v.model} · ${v.voice}`)));$('identities').hidden=false;state.identitiesRevealed=true;persist();$('reveal').hidden=true;}catch(e){note(e.message);}}
$('reveal').onclick=reveal;
$('save').onclick=async()=>{if(!state.voices.some(v=>Object.values(v.ratings).some(x=>x!=null))){note('请先给至少一项评分。');return;}stop();$('save').disabled=true;note('正在保存…');pendingSubmission??=crypto.randomUUID();try{const r=await api('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...state,trialId:manifest.trialId,submissionId:pendingSubmission})});note('评分已保存，我可以从后台读取。回执：'+r.receipt.slice(0,8));$('save').textContent='再次保存评分';}catch(e){note(e.message+'；评分仍保留在本机，可以重试。');}finally{$('save').disabled=false;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault();},{passive:false});
try{const token=new URLSearchParams(location.hash.slice(1)).get('access');if(token){await api('/api/access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});history.replaceState(null,'',location.pathname);}
 manifest=await api('/api/manifest');for(const s of manifest.samples){const b=element('button','',s.title);b.dataset.id=s.id;b.onclick=()=>chooseSample(s.id);$('samples').append(b);}$('voices').replaceChildren(...manifest.voices.map(card));$('preferred').append(choices([['a','声音 A'],['b','声音 B'],['c','声音 C'],['none','都不合格']],state.preferred,id=>{state.preferred=id;}));chooseSample(sampleId);$('save').disabled=false;note('试听就绪；评分后点击保存。');if(state.identitiesRevealed)await reveal();
}catch(e){note(e.message);}
