const storageKey='tsl-kokoro-voice-lab-20261004';
let saved;try{saved=JSON.parse(localStorage.getItem(storageKey)||'null');}catch{}
const sessionId=saved?.sessionId||crypto.randomUUID(),votes=saved?.votes||{},listened=new Set(saved?.listened||[]),choices=saved?.choices||{};
let manifest,tab=saved?.tab||'words',revision=0,submissionId,context,playing,playSerial=0,animation,recoveryApplied=saved?.recoveryApplied;
const buffers=new Map(),$=s=>document.querySelector(s),status=s=>{$('#status').textContent=s;};
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({sessionId,votes,listened:[...listened],choices,tab,recoveryApplied}));}catch{}}
function hasFeedback(v){return v.score!=null||v.qualified!=null||!!v.notes;}
function count(){const n=Object.values(votes).filter(hasFeedback).length;$('#save').disabled=!Object.values(votes).some(v=>v.score);return n;}
async function restoreScreenshots(){
 const recovery=await api('/api/feedback-recovery');if(recoveryApplied===recovery.version||!recovery.ratings.length)return;
 for(const r of recovery.ratings){if(r.kind==='tuning')continue;const local=votes[r.key];votes[r.key]={key:r.key,score:local?.score??r.score??null,qualified:local?.qualified??r.qualified??null,notes:local?.notes||r.notes||''};}
 recoveryApplied=recovery.version;persist();
}
function change(){revision++;submissionId=null;persist();status(`已在本机保存 ${count()} 项反馈，点提交发送。`);}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options});let b;try{b=await r.json();}catch{throw Error('服务暂未响应，请稍后重试。');}if(!r.ok)throw Error(b.error||'请求失败');return b;}
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function button(text,handler,className='bevel'){const b=el('button',text,className);b.type='button';b.addEventListener('click',handler);return b;}
function stop(){playSerial++;cancelAnimationFrame(animation);if(playing){for(const s of playing.sources)try{s.stop();}catch{}playing.button.textContent=playing.label;for(const row of playing.rows||[])row.classList.remove('active');playing=null;}}
async function decoded(id){if(buffers.has(id))return buffers.get(id);const r=await fetch(`/api/audio/${id}`,{credentials:'same-origin'});if(!r.ok)throw Error('音频暂不可用，请稍后重试。');const b=await context.decodeAudioData(await r.arrayBuffer());buffers.set(id,b);return b;}
async function play(ids,b,label,rows=[]){
 if(playing?.button===b){stop();return;}stop();const serial=playSerial;
 try{
  try{if(navigator.audioSession)navigator.audioSession.type='playback';}catch{}
  context??=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'playback'});const resumed=context.resume();
  playing={button:b,label,sources:[],rows};b.textContent='正在载入 · 点按取消';await resumed;
  const data=await Promise.all(ids.map(decoded));if(serial!==playSerial)return;
  let at=context.currentTime+.08;const cues=[];for(let i=0;i<data.length;i++){const s=context.createBufferSource();s.buffer=data[i];s.connect(context.destination);s.start(at);playing.sources.push(s);cues.push({start:at,end:at+data[i].duration,id:ids[i]});at+=data[i].duration+.16;}
  b.textContent='停止播放';
  function tick(){if(serial!==playSerial)return;const now=context.currentTime;for(let i=0;i<cues.length;i++){const c=cues[i];rows[i]?.classList.toggle('active',now>=c.start&&now<c.end);if(now>=c.start&&!listened.has(c.id)){listened.add(c.id);persist();}}if(now>=cues.at(-1).end){stop();return;}animation=requestAnimationFrame(tick);}
  tick();
 }catch(e){if(serial===playSerial){stop();status(e.message||'播放失败，请点按重试。');}}
}
function voiceLabel(v){return `${v.label} · ${v.gender==='female'?'女':'男'} · ${v.accent}`;}
function picker(list,value,handler){const select=el('select');for(const accent of ['美式','英式'])for(const gender of ['female','male']){const subset=list.filter(v=>v.accent===accent&&v.gender===gender);if(!subset.length)continue;const group=el('optgroup');group.label=`${accent} ${gender==='female'?'女声':'男声'}`;for(const v of subset){const option=el('option',v.label);option.value=v.id;group.append(option);}select.append(group);}select.value=value;select.addEventListener('change',()=>{stop();handler(select.value);});return select;}
function rating(key,title){const entry=votes[key]??={key,score:null,qualified:null,notes:''},root=el('div',undefined,'rating');root.dataset.rating=key;root.append(el('p',`${title} · 1 可弃用，3 可用，5 很满意`,'rating-title'));const scores=el('div',undefined,'scores');scores.setAttribute('role','group');scores.setAttribute('aria-label',`${title} 听感评分`);for(let n=1;n<=5;n++){const b=button(String(n),()=>{entry.score=entry.score===n?null:n;for(const c of scores.children)c.setAttribute('aria-pressed',String(Number(c.textContent)===entry.score));change();},'');b.setAttribute('aria-pressed',String(entry.score===n));scores.append(b);}root.append(scores);const qualified=el('div',undefined,'qualified');for(const [text,value]of[['用途合格',true],['不合格',false]]){const b=button(text,()=>{entry.qualified=entry.qualified===value?null:value;for(const c of qualified.children)c.setAttribute('aria-pressed',String(c.dataset.value===String(entry.qualified)));change();});b.dataset.value=String(value);b.setAttribute('aria-pressed',String(entry.qualified===value));qualified.append(b);}root.append(qualified);const notes=el('textarea',undefined,'notes');notes.rows=2;notes.maxLength=2000;notes.placeholder='可选：字音、自然度、角色表现等';notes.setAttribute('aria-label',`${title} 备注`);notes.value=entry.notes;notes.addEventListener('input',()=>{entry.notes=notes.value;change();});root.append(notes);return root;}
function samplePanel(){
 const voiceId=choices[tab]||'heart',v=manifest.voices.find(x=>x.id===voiceId)||manifest.voices[0];choices[tab]=v.id;
 const card=el('section',undefined,'card');card.append(el('h2',tab==='words'?'独立词发音':'短句发音'));const body=el('div',undefined,'body'),choice=el('div',undefined,'voice-choice');
 const list=[...manifest.voices].sort((a,b)=>a.accent.localeCompare(b.accent)||a.gender.localeCompare(b.gender)||a.label.localeCompare(b.label));
 const select=picker(list,v.id,id=>{choices[tab]=id;persist();render();});select.setAttribute('aria-label','选择独立试听音色');
 function move(delta){stop();const index=list.findIndex(x=>x.id===v.id);choices[tab]=list[(index+delta+list.length)%list.length].id;persist();render();}
 choice.append(button('‹',()=>move(-1)),select,button('›',()=>move(1)));body.append(choice,el('p',`${voiceLabel(v)} · ${v.voice}`,'hint'));
 if(tab==='words'){const row=el('div',undefined,'word-buttons');for(const w of manifest.words){const id=`${v.id}-word-${w.id}`,b=button(w.text,()=>play([id],b,w.text));b.disabled=!manifest.ready.includes(id);row.append(b);}body.append(row,el('p','单词单独生成。record 可采用一种读音；切到句子，检查名词与动词能否区分。','hint'));}
 else for(const s of manifest.sentences){const block=el('div',undefined,'sample');block.append(el('p',s.text),el('p',s.hint,'hint'));const id=`${v.id}-sentence-${s.id}`,b=button('播放短句',()=>play([id],b,'播放短句'));b.disabled=!manifest.ready.includes(id);block.append(b);body.append(block);}
 body.append(rating(`${tab}.${v.id}`,`${v.label} · ${tab==='words'?'词汇':'句子'}`));const n=Object.values(votes).filter(x=>x.key.startsWith(tab+'.')&&hasFeedback(x)).length;body.append(el('p',`本类已记录 ${n}/${manifest.voices.length} 个音色；评分、合格判断或评语均保留。`,'count'));card.append(body);return card;
}
function dialoguePanel(){const root=el('div');for(const scene of manifest.scenes){const pair=choices[scene.id]??={female:'heart',male:'michael'},f=manifest.voices.find(v=>v.id===pair.female),m=manifest.voices.find(v=>v.id===pair.male);const card=el('section',undefined,'card');card.append(el('h2',scene.title));const body=el('div',undefined,'body');body.append(el('p',scene.description,'hint'));const selectors=el('div',undefined,'pair');for(const [gender,role]of[['female',scene.femaleRole],['male',scene.maleRole]]){const label=el('label',`${gender==='female'?'女':'男'}声 · ${role}`),select=picker(manifest.voices.filter(v=>v.gender===gender),pair[gender],id=>{pair[gender]=id;persist();render();});select.setAttribute('aria-label',`${scene.title} ${gender==='female'?'女':'男'}声`);label.append(select);selectors.append(label);}body.append(selectors);
 const script=el('details',undefined,'script');script.append(el('summary','展开对话文字'));const rows=scene.turns.map(t=>{const row=el('div',undefined,'turn');row.append(el('span',t.gender==='female'?`${scene.femaleRole} · ${f.label}`:`${scene.maleRole} · ${m.label}`,'role'),el('p',t.text));script.append(row);return row;});const ids=scene.turns.map((t,i)=>`${pair[t.gender]}-scene-${scene.id}-${i+1}`),b=button('播放双人对话',()=>play(ids,b,'播放双人对话',rows),'bevel scene-play');b.disabled=ids.some(id=>!manifest.ready.includes(id));body.append(b,script,rating(`dialogue.${scene.id}.${pair.female}.${pair.male}`,`${f.label} × ${m.label}`));card.append(body);root.append(card);}return root;}
function render(){stop();if(!['words','sentences','dialogue'].includes(tab))tab='words';for(const b of document.querySelectorAll('nav button'))b.setAttribute('aria-pressed',String(b.dataset.tab===tab));$('#content').replaceChildren(tab==='dialogue'?dialoguePanel():samplePanel());count();}
for(const b of document.querySelectorAll('nav button'))b.addEventListener('click',()=>{tab=b.dataset.tab;persist();render();});
$('#save').addEventListener('click',async()=>{const sentRevision=revision;submissionId??=crypto.randomUUID();$('#save').disabled=true;status('正在提交…');try{await api('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({trialId:manifest.trialId,sessionId,submissionId,ratings:Object.values(votes).filter(v=>v.score||v.qualified!==null||v.notes),listened:[...listened]})});status(sentRevision===revision?'评分已提交，我可以读取。':'已提交；刚修改的评分可再次提交。');persist();count();}catch(e){status(e.message);count();}});
$('#export').addEventListener('click',()=>{
 const body={trialId:manifest?.trialId||'voice-lab-20261004',sessionId,exportedAt:new Date().toISOString(),ratings:Object.values(votes).filter(v=>v.score||v.qualified!==null||v.notes),listened:[...listened]},blob=new Blob([JSON.stringify(body,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='kokoro-feedback-2026-10-04.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('已导出评分备份，本机原评分仍保留。');
});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
try{const token=new URLSearchParams(location.hash.slice(1)).get('access');if(token){await api('/api/access',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});history.replaceState(null,'',location.pathname);}manifest=await api('/api/manifest');let recoveryError;try{await restoreScreenshots();}catch(e){recoveryError=e.message;}$('#coverage').textContent=`${manifest.voices.length} 种美式音色 · 11 女声 / 9 男声`;
 const price=manifest.models[0];$('#prices').append(el('p',`按需点读 ${price.lightPrice}；整章配音 ${price.fullPrice}。`));const source=el('a','官方价格');source.href=price.source;source.target='_blank';source.rel='noopener';$('#prices').append(source);render();const n=Object.values(votes).filter(hasFeedback).length;status(recoveryError?'截图反馈暂未载入；本机反馈保留，刷新可重试。':n?`已恢复本机 ${n} 项反馈；可以继续试听、提交或导出备份。`:manifest.ready.length===manifest.assets.length?'选择音色试听；评分会保留，最后统一提交。':'音频正在准备，完成的片段可先试听。');}catch(e){status(e.message);}
