import {createGallery} from './scene.js';
const $=id=>document.getElementById(id),key='tsl-monthly-gallery-v1',read=()=>{try{return JSON.parse(localStorage.getItem(key))||{};}catch{return{};}};
const saved=read(),labels={hall:'全景美术',atmosphere:'动态氛围',coin:'立体纪念币',sound:'象征声音',evolution:'场景介入效果',interaction:'观赏操作',performance:'手机流畅度'},visited=new Set(),summaries={},ratings={...saved.ratings};let gallery,authed=false,posting=false;
function summarize(){if(!gallery)return;const s=gallery.stats();summaries[s.mode+':'+s.progress]={frameP95Ms:s.frameP95Ms,pedestals:s.pedestals,sampleCoins:s.sampleCoins,width:innerWidth,height:innerHeight,selected:s.selected,engine:s.engine};}
function notice(s){$('notice').textContent=s;$('notice').classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').classList.remove('visible'),3500);}
function draft(){try{localStorage.setItem(key,JSON.stringify({ratings,note:$('note').value,pending:saved.pending}));}catch{}}
for(const [k,label]of Object.entries(labels)){const row=document.createElement('label'),s=document.createElement('select');s.id='rating-'+k;s.setAttribute('aria-label',label);s.innerHTML='<option value="">未评价</option>'+[1,2,3,4,5].map(n=>`<option value="${n}">${n}</option>`).join('');s.value=ratings[k]||'';row.append(document.createTextNode(label),s);$('ratings').append(row);s.onchange=()=>{ratings[k]=s.value?Number(s.value):null;draft();};}
$('note').value=saved.note||'';$('note').oninput=draft;
$('menuButton').onclick=()=>{$('options').showModal();$('menuButton').setAttribute('aria-expanded','true');gallery?.suspend(true);};$('options').addEventListener('close',()=>{$('menuButton').setAttribute('aria-expanded','false');if(!$('feedback').open)gallery?.suspend(false);});
$('feedbackButton').onclick=()=>{$('options').close();$('feedback').showModal();gallery?.suspend(true);};$('feedback').addEventListener('close',()=>gallery?.suspend(false));
const states={garden:'苔庭遗迹',poison:'枯庭 · 毒雾侵入',ocean:'海底 · 潮水收回'};
$('environment').onchange=()=>{summarize();gallery?.environment($('environment').value);$('sceneName').textContent=states[$('environment').value];visited.add($('environment').value);};
$('progress').onchange=()=>{summarize();gallery?.progress($('progress').value);$('hallCount').textContent={empty:'1 座展台 · 尚未放币',three:'3 座展台 · 3 枚象征样币',thirty:'30 座展台 · 3 枚样币 / 27 座空台'}[$('progress').value];closeCoin();};
function closeCoin(){gallery?.overview();$('coinCard').hidden=true;$('tour').textContent=gallery?.touring?'暂停环游':'继续环游';}
$('closeCoin').onclick=closeCoin;$('playCoin').onclick=()=>gallery?.playCoin().catch(e=>notice(e.message));
$('previous').onclick=()=>gallery?.next(-1);$('next').onclick=()=>gallery?.next(1);$('tour').onclick=()=>{const on=gallery?.tour();$('tour').textContent=on?'暂停环游':'继续环游';if(on)$('coinCard').hidden=true;};
$('ambience').onclick=async()=>{$('ambience').disabled=true;$('ambience').textContent='准备声音…';try{const on=await gallery?.ambience();$('ambience').setAttribute('aria-pressed',String(on));$('ambience').textContent=on?'关闭环境声':'环境声';}catch{$('ambience').textContent='环境声';notice('声音未能加载，可以稍后再试');}finally{$('ambience').disabled=false;}};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();screen.orientation?.unlock?.();return;}if(!$('experience').requestFullscreen){notice('请横过手机观看；当前浏览器不支持页面全屏');return;}await $('experience').requestFullscreen();try{await screen.orientation?.lock?.('landscape');}catch{notice('请手动横过手机');}}catch{notice('请横过手机观看，浏览器未允许全屏');}};
function feedback(){summarize();return {version:'monthly-gallery-v1',ratings,note:$('note').value,environment:$('environment').value,progress:$('progress').value,visited:[...visited],summaries,scene:gallery?.stats(),device:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,orientation:innerWidth>innerHeight?'landscape':'portrait'}};}
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(feedback(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='monthly-gallery-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('send').onclick=async()=>{if(posting)return;draft();if(!authed){$('feedbackStatus').textContent='请先在第二语言登录，再回来提交。草稿已经保留，也可导出。';return;}posting=true;$('send').disabled=true;const payload=saved.pending||{id:crypto.randomUUID(),feedback:feedback()};saved.pending=payload;draft();try{const r=await fetch('/api/certification-lab/feedback',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(30000)});const v=await r.json();if(!r.ok)throw Error(v.error||'提交未完成');delete saved.pending;draft();$('feedbackStatus').textContent='反馈已保存。';}catch(e){$('feedbackStatus').textContent=e.message+'；草稿已保留，重试将提交同一份反馈。';}finally{posting=false;$('send').disabled=false;}};
async function start(){try{$('retry').hidden=true;gallery=await createGallery($('world'),{status:s=>$('loadStatus').textContent=s,select:c=>{$('coinCard').hidden=false;$('coinName').textContent=c.title;$('coinMeaning').textContent=c.meaning;$('tour').textContent='继续环游';},notice});visited.add('garden');$('loading').hidden=true;window.__monthlyGallery=gallery;}catch(e){$('loadStatus').textContent='展厅加载未完成：'+e.message;$('retry').hidden=false;}}
$('retry').onclick=()=>location.reload();document.addEventListener('visibilitychange',()=>gallery?.suspend(document.hidden||$('options').open||$('feedback').open));window.addEventListener('pagehide',e=>{draft();if(e.persisted)gallery?.suspend(true);else gallery?.dispose();});window.addEventListener('pageshow',e=>{if(e.persisted)gallery?.suspend(document.hidden||$('options').open||$('feedback').open);});
fetch('/api/session',{credentials:'same-origin',cache:'no-store'}).then(r=>r.json()).then(v=>authed=Boolean(v.authenticated)).catch(()=>{});start();

