const B=window.BABYLON,A='./assets/',V=(x=0,y=0,z=0)=>new B.Vector3(x,y,z),C=s=>B.Color3.FromHexString(s);
const themes=[{id:'vegetation',title:'Vegetation · 蕨叶',meaning:'以一片舒展的蕨叶象征植物生长；叶片越过币缘，光点沿叶脉浮动。',asset:'fern_02',color:'#60b781',sound:'vegetation.mp3'}, {id:'aquatic',title:'Aquatic · 鲸影',meaning:'只取水生生命这一意象；鲸体凸出币面，水纹与微泡围绕币缘。',asset:'bronze_whale_statue',color:'#6eaebf',sound:'aquatic.mp3'}, {id:'ordinance',title:'Ordinance · 仪典',meaning:'取宗教仪式这一义项：守护雕塑、书与钟鸣组成象征样件，不复述整章故事。',asset:'gothic_statue',color:'#c4a36a',sound:'ordinance.mp3'}];
export async function createGallery(canvas,{status,select,notice}){
 const engine=new B.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,antialias:true,powerPreference:'high-performance'});engine.setHardwareScalingLevel(1/Math.min(devicePixelRatio,2));const scene=new B.Scene(engine);scene.clearColor=new B.Color4(.027,.045,.036,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.013;scene.fogColor=C('#233b30');
 const camera=new B.ArcRotateCamera('visitor',-Math.PI/2,1.38,15,V(0,3,0),scene);camera.attachControl(canvas,true);camera.lowerRadiusLimit=2;camera.upperRadiusLimit=35;camera.lowerBetaLimit=.25;camera.upperBetaLimit=1.53;camera.wheelPrecision=30;camera.pinchPrecision=65;camera.panningSensibility=0;camera.inertia=.83;camera.minZ=.12;camera.fov=.83;
 const ambient=new B.HemisphericLight('sky-light',V(0,1,0),scene);ambient.intensity=.35;ambient.diffuse=C('#c3d2be');ambient.groundColor=C('#1c2b24');
 const sun=new B.DirectionalLight('moon',V(-.35,-1,.3),scene);sun.position=V(12,25,-12);sun.diffuse=C('#bbcfbf');sun.intensity=1.6;
 const light=new B.PointLight('altar-light',V(0,4,0),scene);light.diffuse=C('#d7a65f');light.intensity=55;light.range=22;
 const accent=new B.PointLight('moving-light',V(7,3,0),scene);accent.diffuse=C('#5ad799');accent.intensity=12;accent.range=12;
 const shadows=new B.ShadowGenerator(1024,sun);shadows.usePercentageCloserFiltering=true;shadows.filteringQuality=B.ShadowGenerator.QUALITY_LOW;shadows.bias=.001;shadows.normalBias=.03;
 const env=B.CubeTexture.CreateFromPrefilteredData(A+'cloister.env',scene);scene.environmentTexture=env;scene.environmentIntensity=.55;
 const pipeline=new B.DefaultRenderingPipeline('gallery',true,scene,[camera]);pipeline.fxaaEnabled=true;pipeline.bloomEnabled=true;pipeline.bloomWeight=.22;pipeline.bloomThreshold=1;pipeline.bloomKernel=32;pipeline.bloomScale=.5;pipeline.samples=1;pipeline.imageProcessing.contrast=1.13;pipeline.imageProcessing.exposure=1.12;pipeline.imageProcessing.toneMappingEnabled=true;pipeline.imageProcessing.toneMappingType=B.ImageProcessingConfiguration.TONEMAPPING_ACES;
 const viewingLight=new B.PointLight('coin-viewing-light',camera.position.clone(),scene);viewingLight.diffuse=C('#e0e5cd');viewingLight.intensity=22;viewingLight.range=8;const glow=new B.GlowLayer('emissive-details',scene,{mainTextureRatio:.35,blurKernelSize:32});glow.intensity=.45;
 function material(name,color,metal=0,rough=.7){const m=new B.PBRMaterial(name,scene);m.albedoColor=C(color);m.metallic=metal;m.roughness=rough;return m;}
 const stone=material('dark-polished-stone','#34443c',.15,.42),bronze=material('antique-bronze','#af8751',.9,.28),darkGold=material('engraved-bronze','#51442b',.82,.4),silver=material('satin-silver','#bdc6b7',.92,.23),obsidian=material('obsidian','#0b1614',.58,.18),emission=material('altar-energy','#436757',.2,.32);emission.emissiveColor=C('#6ea97e');
 const floor=B.MeshBuilder.CreateGround('courtyard',{width:75,height:75},scene);floor.material=stone;floor.receiveShadows=true;floor.position.y=-.06;
 const groundTexture=new B.DynamicTexture('stone-grain',{width:512,height:512},scene,false),ctx=groundTexture.getContext();ctx.fillStyle='#475247';ctx.fillRect(0,0,512,512);for(let i=0;i<4000;i++){const n=34+Math.floor(Math.random()*33);ctx.fillStyle=`rgba(${n},${n+5},${n},.4)`;ctx.fillRect(Math.random()*512,Math.random()*512,Math.random()*4+1,1);}ctx.strokeStyle='#212d25';ctx.lineWidth=3;for(let i=0;i<512;i+=128){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(512,i);ctx.stroke();for(let x=(i/128%2)*64;x<512;x+=128){ctx.beginPath();ctx.moveTo(x,i);ctx.lineTo(x,i+128);ctx.stroke();}}groundTexture.update();groundTexture.uScale=groundTexture.vScale=12;stone.albedoTexture=groundTexture;
 status('加载精细回廊');const hall=await B.SceneLoader.ImportMeshAsync(null,A,'cloister.glb',scene),architecture=new B.TransformNode('upright-cloister',scene);hall.meshes[0].parent=architecture;architecture.rotation.x=-Math.PI/2;architecture.computeWorldMatrix(true);const bounds=architecture.getHierarchyBoundingVectors(true),center=bounds.min.add(bounds.max).scale(.5),scale=32/Math.max(bounds.max.x-bounds.min.x,bounds.max.z-bounds.min.z);architecture.scaling.scaleInPlace(scale);architecture.position=V(-center.x*scale,0,-center.z*scale);for(const m of hall.meshes){m.isPickable=false;m.receiveShadows=true;if(m.material){m.material.backFaceCulling=false;if('roughness'in m.material)m.material.roughness=.95;}}
 // Authored scanned architecture is reused as one object, not rebuilt from boxes.
 const wing=new B.TransformNode('cloister-wing',scene);architecture.parent=wing;wing.position.x=-27;const opposite=wing.clone('opposite-cloister',null,false);opposite.rotation.y=Math.PI;opposite.position.x=27;const hallRoots=[wing,opposite];for(const [angle,x,z]of [[Math.PI/2,0,27],[-Math.PI/2,0,-27]]){const next=wing.clone('cloister-cross-wing',null,false);next.rotation.y=angle;next.position.x=x;next.position.z=z;hallRoots.push(next);}
 status('准备雕塑与植物');const containers={};await Promise.all([...themes.map(async t=>containers[t.asset]=await B.SceneLoader.LoadAssetContainerAsync(A+t.asset+'/',t.asset+'.gltf',scene)),(async()=>containers.marine=await B.SceneLoader.LoadAssetContainerAsync(A,'shark.glb',scene))()]);
 function model(asset,parent,size=1){const set=containers[asset].instantiateModelsToScene(n=>'copy-'+n,false,{doNotInstantiate:true});const root=new B.TransformNode('sculpture',scene);for(const n of set.rootNodes)n.parent=root;root.computeWorldMatrix(true);const q=root.getHierarchyBoundingVectors(true),d=q.max.subtract(q.min),k=size/Math.max(d.x,d.y,d.z),p=q.min.add(q.max).scale(.5);for(const n of set.rootNodes){n.position.subtractInPlace(p);n.scaling.scaleInPlace(k);n.position.scaleInPlace(k);}root.parent=parent;root.metadata={animations:set.animationGroups};return root;}
 const plants=[];for(let i=0;i<16;i++){const p=new B.TransformNode('fern-bed',scene),angle=i/16*Math.PI*2;p.position=V(Math.cos(angle)*14,.15,Math.sin(angle)*10);p.rotation.y=angle;const mesh=model('fern_02',p,2.2+(i%3)*.4);plants.push(p);}
 const diskTemplates=new Map();function disk(name,diameter,height,mat,parent,y=0){const key=name+diameter+height+mat.name;let m;if(diskTemplates.has(key))m=diskTemplates.get(key).createInstance(name);else{m=B.MeshBuilder.CreateCylinder(name,{diameter,height,tessellation:64},scene);m.material=mat;diskTemplates.set(key,m);}m.parent=parent;m.position.y=y;m.receiveShadows=true;return m;}
 const altar=new B.TransformNode('central-altar',scene);disk('altar-plinth',5,.2,stone,altar,.1);disk('altar-step',4.2,.24,obsidian,altar,.27);disk('altar-band',3.7,.06,bronze,altar,.42);disk('altar-top',3.5,.2,stone,altar,.55);
 const altarRings=[];for(let i=0;i<3;i++){const r=B.MeshBuilder.CreateTorus('levitating-orrery',{diameter:2.5+i*.6,thickness:.022,tessellation:96},scene);r.material=i===1?emission:bronze;r.parent=altar;r.position.y=1.45+i*.5;r.rotation.x=.2+i*.5;altarRings.push(r);}
 const crystal=B.MeshBuilder.CreatePolyhedron('altar-crystal',{type:1,size:.8},scene);crystal.parent=altar;crystal.position.y=2.2;crystal.material=emission;shadows.addShadowCaster(crystal);
 const centralFigure=model('gothic_statue',altar,3.5);centralFigure.position=V(0,2.45,0);centralFigure.setEnabled(true);
 const particleTexture=new B.DynamicTexture('spark',{width:64,height:64},scene,false),pc=particleTexture.getContext(),gradient=pc.createRadialGradient(32,32,1,32,32,31);gradient.addColorStop(0,'white');gradient.addColorStop(.2,'rgba(220,255,210,.9)');gradient.addColorStop(1,'transparent');pc.fillStyle=gradient;pc.fillRect(0,0,64,64);particleTexture.update();
 const motes=new B.ParticleSystem('air-motes',180,scene);motes.particleTexture=particleTexture;motes.emitter=V(0,0,0);motes.minEmitBox=V(-15,.5,-12);motes.maxEmitBox=V(15,8,12);motes.color1=new B.Color4(.7,.9,.55,.25);motes.color2=new B.Color4(.9,.75,.35,.4);motes.colorDead=new B.Color4(.2,.3,.15,0);motes.minSize=.035;motes.maxSize=.12;motes.minLifeTime=9;motes.maxLifeTime=16;motes.emitRate=14;motes.direction1=V(-.03,.08,-.03);motes.direction2=V(.03,.18,.03);motes.minEmitPower=.5;motes.maxEmitPower=1;motes.updateSpeed=.015;motes.start();
 const mist=new B.ParticleSystem('altar-mist',60,scene);mist.particleTexture=particleTexture;mist.emitter=V(0,.8,0);mist.minEmitBox=V(-1,0,-1);mist.maxEmitBox=V(1,.3,1);mist.color1=new B.Color4(.24,.65,.43,.05);mist.color2=new B.Color4(.6,.65,.2,.035);mist.colorDead=new B.Color4(0,0,0,0);mist.minSize=1;mist.maxSize=2.5;mist.minLifeTime=3;mist.maxLifeTime=5;mist.emitRate=12;mist.direction1=V(-.2,.6,-.2);mist.direction2=V(.2,.8,.2);mist.minEmitPower=.4;mist.maxEmitPower=.9;mist.blendMode=B.ParticleSystem.BLENDMODE_STANDARD;mist.start();
 // A sky shader remains visible above the open arcade, including underwater shafts.
 B.Effect.ShadersStore.gallerySkyVertexShader='precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 p;void main(){p=position;gl_Position=worldViewProjection*vec4(position,1.);}';
 B.Effect.ShadersStore.gallerySkyFragmentShader='precision highp float;varying vec3 p;uniform float time;uniform float mode;void main(){vec3 n=normalize(p);vec2 cell=floor(vec2(atan(n.z,n.x),asin(n.y))*170.);float h=fract(sin(dot(cell,vec2(12.9898,78.233)))*43758.5453);float stars=step(.998,h)*pow(max(0.,1.-length(fract(vec2(atan(n.z,n.x),asin(n.y))*170.)-.5)*2.),3.);float veil=sin(n.x*8.+sin(n.z*6.+time*.025))*sin(n.z*6.+time*.02);vec3 col=mix(vec3(.016,.035,.042),vec3(.075,.14,.09),max(0.,n.y));col+=vec3(.03,.08,.04)*max(0.,veil)*smoothstep(0.,.8,n.y);col+=stars*.28;col=mix(col,vec3(.008,.085,.105)+vec3(.04,.13,.1)*pow(max(0.,sin(n.x*14.+time*.05)),8.),mode);gl_FragColor=vec4(col,1.);}';
 const skyMat=new B.ShaderMaterial('living-sky',scene,{vertex:'gallerySky',fragment:'gallerySky'},{attributes:['position'],uniforms:['worldViewProjection','time','mode']});skyMat.backFaceCulling=false;skyMat.setFloat('mode',0);const sky=B.MeshBuilder.CreateSphere('sky',{diameter:160,segments:24},scene);sky.material=skyMat;sky.isPickable=false;
 B.Effect.ShadersStore.galleryWaterVertexShader='precision highp float;attribute vec3 position;attribute vec2 uv;uniform mat4 worldViewProjection;varying vec2 v;void main(){v=uv;gl_Position=worldViewProjection*vec4(position,1.);}';
 B.Effect.ShadersStore.galleryWaterFragmentShader='precision highp float;varying vec2 v;uniform float time;uniform float mode;uniform sampler2D reflectionSampler;void main(){vec2 q=v+vec2(sin(v.y*45.+time)*.007,cos(v.x*38.-time*.8)*.008);vec3 r=texture2D(reflectionSampler,q).rgb;float c=pow(abs(sin(v.x*12.+sin(v.y*15.+time*.3))*sin(v.y*13.-time*.5)),9.);gl_FragColor=vec4(mix(vec3(.018,.08,.06),r,.62)+vec3(.1,.24,.19)*c,.85);}';
 const mirror=new B.MirrorTexture('water-reflection',256,scene,true);mirror.mirrorPlane=new B.Plane(0,-1,0,.08);mirror.renderList=hall.meshes.filter(m=>m.getTotalVertices()>0).concat(opposite.getChildMeshes(),crystal);mirror.level=.7;const water=B.MeshBuilder.CreateGround('water',{width:12,height:9,subdivisions:1},scene);water.position.y=.08;water.material=new B.ShaderMaterial('moving-water',scene,{vertex:'galleryWater',fragment:'galleryWater'},{attributes:['position','uv'],uniforms:['worldViewProjection','time','mode'],samplers:['reflectionSampler'],needAlphaBlending:true});water.material.setTexture('reflectionSampler',mirror);water.isPickable=false;
 const stations=[],coins=[],glimmers=[];let selected=-1,progress='empty',mode='garden',touring=!matchMedia('(prefers-reduced-motion: reduce)').matches,paused=false,time=0,lastTime=performance.now(),frames=[],targetTransition=null,tourDelay=0,audio=null,ambientEnabled=false,disposed=false;
 function coin(theme,parent,index){const r=new B.TransformNode('coin-'+theme.id,scene);r.parent=parent;r.position.y=2.25;const plate=disk('coin-body',1.55,.055,obsidian,r);plate.rotation.x=Math.PI/2;for(const radius of [1.53,1.44,1.24]){const border=B.MeshBuilder.CreateTorus('milled-rim',{diameter:radius,thickness:radius===1.53?.035:.012,tessellation:96},scene);border.parent=r;border.rotation.x=Math.PI/2;border.material=bronze;}
  for(let i=0;i<48;i++){const tick=B.MeshBuilder.CreateBox('edge-notch',{width:.009,height:.045,depth:.024},scene),a=i/48*Math.PI*2;tick.parent=r;tick.position=V(Math.cos(a)*.734,Math.sin(a)*.734,.035);tick.rotation.z=a-Math.PI/2;tick.material=darkGold;tick.isPickable=false;}
  const relief=new B.TransformNode('raised-relief',scene);relief.parent=r;relief.position.z=.09;const sculpture=model(theme.asset,relief,1.2);if(theme.asset==='fern_02'){sculpture.rotation.x=Math.PI/2;relief.scaling.z=.32;sculpture.scaling.x=.85;sculpture.position.y=.03;}else if(theme.asset==='bronze_whale_statue'){sculpture.rotation.z=-.3;relief.scaling.z=.42;sculpture.position.y=.06;}else{relief.scaling.z=.4;sculpture.position.y=0;}for(const m of sculpture.getChildMeshes()){m.material=theme.asset==='fern_02'?m.material:silver;if(m.material&&theme.asset==='fern_02'){m.material=m.material.clone('coin-leaf');m.material.metallic=.25;m.material.roughness=.4;}shadows.addShadowCaster(m);}
  const reverse=disk('reverse-seal',.63,.012,bronze,r);reverse.rotation.x=Math.PI/2;reverse.position.z=-.04;const lightRing=B.MeshBuilder.CreateTorus('theme-halo',{diameter:1.82,thickness:.006,tessellation:96},scene),halo=material('halo-'+theme.id,theme.color,.4,.3);halo.emissiveColor=C(theme.color).scale(1.3);lightRing.material=halo;lightRing.parent=r;lightRing.rotation.x=Math.PI/2;
  for(const m of r.getChildMeshes()){m.metadata={coin:index};m.isPickable=true;}coins.push({root:r,theme,sculpture,halo:lightRing});return r;
 }
 function station(i){const node=new B.TransformNode('chapter-pedestal',scene),a=i/30*Math.PI*2-Math.PI/2;node.position=V(Math.cos(a)*12,0,Math.sin(a)*9.5);node.rotation.y=-a-Math.PI/2;disk('pedestal-foot',2,.13,stone,node,.065);disk('pedestal-bevel',1.7,.18,obsidian,node,.22);disk('pedestal-shaft',1.1,1.2,stone,node,.9);disk('pedestal-neck',1.25,.06,bronze,node,1.45);disk('pedestal-crown',1.55,.2,stone,node,1.58);disk('pedestal-inlay',1.4,.012,bronze,node,1.69);
  const rune=B.MeshBuilder.CreateTorus('pedestal-sigil',{diameter:1.15,thickness:.018,tessellation:64},scene);rune.parent=node;rune.position.y=1.72;rune.material=emission;
  stations.push(node);if(i<3)coin(themes[i],node,i);
 }
 for(let i=0;i<30;i++)station(i);
 function setProgress(value){progress=value;for(let i=0;i<30;i++)stations[i].setEnabled(i<(value==='empty'?1:value==='three'?3:30));for(const c of coins)c.root.setEnabled(value!=='empty');selected=-1;}
 setProgress('empty');
 const fish=[];for(let i=0;i<4;i++){const p=model('marine',null,1.6);p.setEnabled(false);fish.push(p);}
 function environment(value){mode=value;scene.fogColor=C(value==='ocean'?'#0d4149':value==='poison'?'#2d3520':'#233b30');scene.fogDensity=value==='ocean'?.021:.013;skyMat.setFloat('mode',value==='ocean'?1:0);ambient.diffuse=C(value==='poison'?'#b3b988':value==='ocean'?'#79baca':'#c3d2be');sun.diffuse=ambient.diffuse;accent.diffuse=C(value==='poison'?'#a9cf3d':value==='ocean'?'#68d5e7':'#5ad799');light.diffuse=C(value==='poison'?'#a6ba4f':value==='ocean'?'#6bccde':'#d7a65f');motes.color1=value==='ocean'?new B.Color4(.4,.8,1,.28):new B.Color4(.7,.9,.55,.25);mist.color1=value==='poison'?new B.Color4(.42,.56,.13,.14):new B.Color4(.24,.65,.43,.05);centralFigure.setEnabled(true);crystal.setEnabled(true);for(const p of plants){for(const m of p.getChildMeshes()){if(m.material&&!m.material.name.startsWith('plant-evolving'))m.material=m.material.clone('plant-evolving');if(m.material?.albedoColor)m.material.albedoColor=C(value==='poison'?'#776144':value==='ocean'?'#5a9286':'#ffffff');}}for(const f of fish){f.setEnabled(value==='ocean');for(const [i,g]of f.metadata.animations.entries()){if(i===0&&value==='ocean')g.start(true,.7);else g.stop();}}water.scaling=V(value==='ocean'?3.5:1,1,value==='ocean'?3.5:1);pipeline.imageProcessing.colorCurvesEnabled=value==='poison';const curves=new B.ColorCurves();curves.globalSaturation=-65;curves.globalHue=75;curves.globalDensity=24;pipeline.imageProcessing.colorCurves=curves;mist.emitRate=value==='poison'?28:12;mist.minSize=value==='poison'?2.5:1;mist.maxSize=value==='poison'?5:2.5;water.setEnabled(value!=='poison');if(ambientEnabled)playAmbient().catch(()=>notice('环境声音未能加载'));}
 const flare=new B.LensFlareSystem('altar-flare',light,scene),glint=new B.LensFlare(.08,1,new B.Color3(.25,.35,.16),null,flare);glint.texture=particleTexture;flare.isEnabled=true;
 function focus(i){if(progress==='empty'){notice('这座展台等待认证后的纪念币。');return;}selected=((i%3)+3)%3;touring=false;coins[selected].root.computeWorldMatrix(true);const world=coins[selected].root.getAbsolutePosition(),face=B.Vector3.TransformNormal(V(0,0,1),coins[selected].root.getWorldMatrix()).normalize(),angle=Math.atan2(face.z,face.x);camera.lowerRadiusLimit=2;camera.upperRadiusLimit=8;targetTransition={target:world.clone(),radius:innerWidth>innerHeight?3.7:5.7,alpha:camera.alpha+Math.atan2(Math.sin(angle-camera.alpha),Math.cos(angle-camera.alpha)),beta:Math.PI/2};select(coins[selected].theme);}
 let start=null;canvas.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY,t:performance.now()};tourDelay=performance.now()+8000;});canvas.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start.x,e.clientY-start.y)>10||performance.now()-start.t>600)return;const pick=scene.pick(e.offsetX,e.offsetY,m=>Number.isInteger(m.metadata?.coin));if(pick?.hit)focus(pick.pickedMesh.metadata.coin);});
 function overview(){selected=-1;camera.lowerRadiusLimit=8;camera.upperRadiusLimit=18;targetTransition={target:V(0,3,0),radius:15,alpha:camera.alpha,beta:1.38};}
 async function getAudio(){if(disposed)throw Error('展厅已关闭');audio||=new AudioContext();if(!paused)await audio.resume();return audio;}
 const buffers=new Map();let voices=[],ambientVoice=null,ambientGain=null;
 async function buffer(name){if(!buffers.has(name)){const r=await fetch(A+name);if(!r.ok)throw Error('声音加载失败');const a=await getAudio();buffers.set(name,await a.decodeAudioData(await r.arrayBuffer()));}return buffers.get(name);}
 async function playCoin(){if(selected<0){notice('先在选项中放入样币，再点按近看。');return;}const who=selected,a=await getAudio(),b=await buffer(coins[who].theme.sound);if(selected!==who||disposed)return;for(const v of voices)v.stop();voices=[];const s=a.createBufferSource(),g=a.createGain();s.buffer=b;g.gain.value=.65;s.connect(g).connect(a.destination);s.start();voices.push(s);s.onended=()=>voices=voices.filter(v=>v!==s);}
 let soundGeneration=0;
 async function playAmbient(){const generation=++soundGeneration,a=await getAudio(),b=await buffer(mode==='ocean'?'ambient-ocean.mp3':'ambient-garden.mp3');if(!ambientEnabled||disposed||generation!==soundGeneration)return;ambientVoice?.stop();const s=a.createBufferSource(),g=a.createGain();s.buffer=b;s.loop=true;g.gain.setValueAtTime(0,a.currentTime);g.gain.linearRampToValueAtTime(.2,a.currentTime+1.5);s.connect(g).connect(a.destination);ambientVoice=s;ambientGain=g;s.start();}
 function stopAudio(){ambientVoice?.stop();ambientVoice=null;for(const v of voices)v.stop();voices=[];}
 function render(){if(paused||disposed)return;const now=performance.now(),lastTimeBefore=lastTime,dt=Math.min((now-lastTime)/1000,.06);lastTime=now;time+=dt;if(frames.length>=180)frames.shift();frames.push(now-lastTimeBefore);skyMat.setFloat('time',time);water.material.setFloat('time',time);for(let i=0;i<altarRings.length;i++){altarRings[i].rotation.y+=dt*(.08+i*.03);altarRings[i].rotation.z=Math.sin(time*.25+i)*.3;}crystal.rotation.y+=dt*.15;crystal.position=V(Math.cos(time*.3)*1.4,2.2+Math.sin(time*.7)*.12,Math.sin(time*.3)*1.4);crystal.scaling.setAll(.45);accent.position=V(Math.cos(time*.13)*7,3+Math.sin(time*.3),Math.sin(time*.13)*5);for(let i=0;i<coins.length;i++){const c=coins[i];c.root.position.y=2.65+Math.sin(time*.7+i)*.07;if(selected!==i)c.root.rotation.y+=dt*.1;c.halo.rotation.z+=dt*.14;}for(let i=0;i<plants.length;i++){plants[i].rotation.z=(mode==='poison'?(i%2?.35:-.35):0)+Math.sin(time*.45+i)*.015;plants[i].scaling.y=mode==='poison'?.5:1;}for(let i=0;i<fish.length;i++){const a=time*.055+i*1.2;fish[i].position=V(Math.cos(a)*10,3+i*.5+Math.sin(time*.2+i)*.3,Math.sin(a)*7);fish[i].rotation.y=-a-Math.PI/2;}if(targetTransition){const f=1-Math.exp(-dt*3.5);camera.target=B.Vector3.Lerp(camera.target,targetTransition.target,f);camera.radius+=(targetTransition.radius-camera.radius)*f;camera.alpha+=(targetTransition.alpha-camera.alpha)*f;camera.beta+=(targetTransition.beta-camera.beta)*f;if(B.Vector3.Distance(camera.target,targetTransition.target)<.005&&Math.abs(camera.radius-targetTransition.radius)<.01)targetTransition=null;}else if(touring&&now>tourDelay)camera.alpha+=dt*.018;viewingLight.position.copyFrom(camera.position);viewingLight.intensity=selected>=0?22:0;scene.render();}
 engine.runRenderLoop(render);let landscape=innerWidth>innerHeight;const resize=()=>{engine.resize();const next=innerWidth>innerHeight;if(next!==landscape&&selected>=0)targetTransition={target:camera.target.clone(),radius:next?3.7:5.7,alpha:camera.alpha,beta:camera.beta};landscape=next;};window.addEventListener('resize',resize);engine.onContextLostObservable.add(()=>notice('画面暂时中断，请重新打开展厅'));status('点亮展厅');await scene.whenReadyAsync();
 return {get touring(){return touring;},environment,progress:setProgress,next(d){focus(selected<0?0:selected+d);},overview,tour(){if(selected>=0)overview();return touring=!touring;},playCoin,async ambience(){ambientEnabled=!ambientEnabled;if(ambientEnabled){try{await playAmbient();}catch(e){ambientEnabled=false;throw e;}}else{ambientVoice?.stop();ambientVoice=null;}return ambientEnabled;},suspend(value){paused=value;lastTime=performance.now();if(value){audio?.suspend();}else if(audio?.state==='suspended'){audio.resume().catch(()=>{});}},stats(){const sorted=[...frames].sort((a,b)=>a-b);return {mode,progress,selected,touring,frameP95Ms:Math.round((sorted[Math.floor(sorted.length*.95)]||0)*10)/10,meshes:scene.meshes.length,vertices:scene.getTotalVertices(),pedestals:progress==='empty'?1:progress==='three'?3:30,sampleCoins:progress==='empty'?0:3,engine:'Babylon.js 9.30.0 WebGL',context:engine.webGLVersion,renderer:engine.getGlInfo().renderer,loadedSoundFiles:buffers.size,coinAudioPlaying:voices.length>0,ambientEnabled,architectureBounds:{min:bounds.min.asArray(),max:bounds.max.asArray()},sculptureBounds:coins.map(c=>{const q=c.sculpture.getHierarchyBoundingVectors(true);return {min:q.min.asArray(),max:q.max.asArray()};}),camera:{position:camera.position.asArray(),target:camera.target.asArray(),alpha:camera.alpha,beta:camera.beta,radius:camera.radius}};},dispose(){disposed=true;stopAudio();audio?.close();window.removeEventListener('resize',resize);scene.dispose();engine.dispose();}};
}










