import RAPIER from '../certification/vendor/rapier.js';
import {clamp,length,fromTo,slerp,rotate} from './motion.js';
await RAPIER.init();
let world=null,queue=null,jar=null,coins=[],handles=new Map(),paused=true,timer=null,accumulator=0,last=0,sequence=0,steps=0,impacts=0,inputAt=0,gravity={x:0,y:-9.81,z:0},linear={x:0,y:0,z:0},offset={x:0,y:0,z:0},velocity={x:0,y:0,z:0},rotation={x:0,y:0,z:0,w:1},manual=null,started=0,simTime=0,physicsTimes=[],droppedMs=0,awaitingFrame=false,unsent=false,pendingHits=[];
const STEP=1/60,CENTRE=2.35;
function initialize(count){clearTimeout(timer);world?.free();queue?.free();world=new RAPIER.World({x:0,y:-9.81,z:0});world.timestep=STEP;world.numSolverIterations=6;world.maxCcdSubsteps=2;queue=new RAPIER.EventQueue(true);jar=world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(0,CENTRE,0));
 world.createCollider(RAPIER.ColliderDesc.cylinder(.10,1.52).setTranslation(0,-2.13,0).setFriction(.35),jar);world.createCollider(RAPIER.ColliderDesc.cylinder(.08,1.52).setTranslation(0,2.13,0).setFriction(.35),jar);
 for(let i=0;i<32;i++){const t=i*Math.PI/16;world.createCollider(RAPIER.ColliderDesc.cuboid(.155,2.13,.06).setTranslation(Math.sin(t)*1.54,0,Math.cos(t)*1.54).setRotation({x:0,y:Math.sin(t/2),z:0,w:Math.cos(t/2)}).setFriction(.32),jar);}
 coins=[];handles.clear();const spots=[];for(let row=-2;row<=2;row++)for(let col=-2;col<=2;col++){const x=(col+(Math.abs(row)%2)*.5)*.56,z=row*.56*Math.sqrt(3)/2;if(Math.hypot(x,z)<1.20)spots.push({x,z});}
 for(let i=0;i<count;i++){const s=spots[i%spots.length],layer=Math.floor(i/spots.length),yaw=(i*2.399963)%6.283,tilt=.05*Math.sin(i*7.2),q={x:Math.sin(tilt/2)*Math.cos(yaw/2),y:Math.cos(tilt/2)*Math.sin(yaw/2),z:-Math.sin(tilt/2)*Math.sin(yaw/2),w:Math.cos(tilt/2)*Math.cos(yaw/2)};
  const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(s.x+Math.sin(i)*.014,.42+layer*.145,s.z+Math.cos(i*2.7)*.014).setRotation(q).setLinearDamping(.15).setAngularDamping(.22).setCcdEnabled(true));
  const collider=world.createCollider(RAPIER.ColliderDesc.cylinder(.045,.26).setDensity(1).setFriction(.38).setRestitution(.13).setActiveEvents(RAPIER.ActiveEvents.COLLISION_EVENTS|RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(.1),body);coins.push({body,collider});handles.set(collider.handle,i);
 }
 offset={x:0,y:0,z:0};velocity={x:0,y:0,z:0};rotation={x:0,y:0,z:0,w:1};gravity={x:0,y:-9.81,z:0};linear={x:0,y:0,z:0};manual=null;steps=impacts=sequence=simTime=droppedMs=0;physicsTimes=[];awaitingFrame=false;unsent=false;pendingHits=[];accumulator=0;started=last=performance.now();paused=false;snapshot([]);tick();
}
function snapshot(hits){pendingHits.push(...hits);pendingHits=pendingHits.sort((a,b)=>b.strength-a.strength).slice(0,3);if(awaitingFrame){unsent=true;return;}awaitingFrame=true;unsent=false;hits=pendingHits;pendingHits=[];const transforms=new Float32Array(coins.length*7);let sleeping=0,maxRadius=0,minY=Infinity,maxY=-Infinity;const jq=jar.rotation(),jp=jar.translation(),inverse={x:-jq.x,y:-jq.y,z:-jq.z,w:jq.w};for(let i=0;i<coins.length;i++){const b=coins[i].body,p=b.translation(),q=b.rotation(),local=rotate({x:p.x-jp.x,y:p.y-jp.y,z:p.z-jp.z},inverse);transforms.set([p.x,p.y,p.z,q.x,q.y,q.z,q.w],i*7);sleeping+=Number(b.isSleeping());maxRadius=Math.max(maxRadius,Math.hypot(local.x,local.z));minY=Math.min(minY,local.y);maxY=Math.max(maxY,local.y);}
 const sorted=[...physicsTimes].sort((a,b)=>a-b);postMessage({type:'snapshot',sequence:++sequence,transforms,jar:{position:jp,rotation:jq},hits,stats:{count:coins.length,steps,impacts,sleeping,physicsP95Ms:sorted[Math.floor(sorted.length*.95)]||0,droppedMs,simTimeMs:Math.round(simTime*1000),elapsedMs:Math.round(performance.now()-started),bounds:{maxRadius,minY,maxY}}},[transforms.buffer]);}
function tick(){if(paused||!world)return;const now=performance.now(),rawDt=(now-last)/1000,dt=Math.min(.1,rawDt);droppedMs+=Math.max(0,rawDt-dt)*1000;last=now;accumulator+=dt;const hits=[],begin=performance.now();let n=0,moved=false;
 while(accumulator>=STEP&&n<6){const fresh=now-inputAt<250,a=fresh?linear:{x:0,y:0,z:0},target=fromTo(gravity,{x:0,y:-9.81,z:0}),old=rotation;const angularDistance=2*Math.acos(clamp(Math.abs(old.x*target.x+old.y*target.y+old.z*target.z+old.w*target.w),-1,1));rotation=slerp(rotation,target,Math.min(1-Math.exp(-STEP/.08),angularDistance>1e-6?3*STEP/angularDistance:1));const rotating=Math.abs(old.x-rotation.x)+Math.abs(old.y-rotation.y)+Math.abs(old.z-rotation.z)+Math.abs(old.w-rotation.w)>.0005;
  const worldAcceleration=rotate(a,rotation);
  for(const k of ['x','y','z']){velocity[k]+=((fresh?worldAcceleration[k]*1.8:0)-offset[k]*36-velocity[k]*10)*STEP;offset[k]=clamp(offset[k]+velocity[k]*STEP,-.48,.48);if(Math.abs(offset[k])>=.48)velocity[k]=0;}
  let p={x:offset.x,y:CENTRE+offset.y,z:offset.z};if(manual){const phase=simTime-manual.start;if(phase<.75){p.x+=Math.sin(phase*18)*manual.strength*.22*Math.sin(Math.PI*phase/.75);p.z+=Math.sin(phase*13)*manual.strength*.08*Math.sin(Math.PI*phase/.75);}else manual=null;}
  const prior=jar.translation(),translationChanged=length({x:p.x-prior.x,y:p.y-prior.y,z:p.z-prior.z})>.0003;moved||=rotating||translationChanged;
  jar.setNextKinematicTranslation(p);jar.setNextKinematicRotation(rotation);if(rotating||translationChanged)for(const {body}of coins)body.wakeUp();
  const speeds=new Map(coins.map(({body,collider})=>[collider.handle,body.linvel()]));const began=new Set();world.step(queue);steps++;simTime+=STEP;queue.drainCollisionEvents((a,b,on)=>{if(on)began.add(a<b?`${a}:${b}`:`${b}:${a}`);});
  queue.drainContactForceEvents(e=>{const a=e.collider1(),b=e.collider2(),key=a<b?`${a}:${b}`:`${b}:${a}`;if(!began.has(key)||simTime<.8)return;const va=speeds.get(a)||jar.linvel(),vb=speeds.get(b)||jar.linvel(),relative=length({x:va.x-vb.x,y:va.y-vb.y,z:va.z-vb.z});if(relative<.25)return;const strength=clamp(relative/4,.04,1);hits.push({kind:handles.has(a)&&handles.has(b)?'metal':'glass',strength});impacts++;});
  accumulator-=STEP;n++;
 }
 physicsTimes.push(performance.now()-begin);if(physicsTimes.length>120)physicsTimes.shift();if(accumulator>.12){droppedMs+=(accumulator-.12)*1000;accumulator=.12;}
 if(n)snapshot(hits.sort((a,b)=>b.strength-a.strength).slice(0,3));const asleep=coins.every(c=>c.body.isSleeping());if(asleep&&!moved&&!manual&&length(velocity)<.003){timer=null;return;}timer=setTimeout(tick,asleep&&!moved?60:Math.max(0,16-(performance.now()-begin)));
}
function wake(){if(!paused&&!timer){last=performance.now();timer=setTimeout(()=>{timer=null;tick();},0);}}
onmessage=({data})=>{try{if(data.type==='ack'){awaitingFrame=false;if(unsent)snapshot([]);}else if(data.type==='init'){if(![32,128,500].includes(data.count))throw Error('Invalid coin count');initialize(data.count);}else if(data.type==='input'){gravity=data.gravity;linear=data.linear;inputAt=performance.now();wake();}else if(data.type==='shake'){manual={start:simTime,strength:clamp(data.strength,.3,2)};wake();}else if(data.type==='pause'){paused=data.value;clearTimeout(timer);timer=null;if(!paused){last=performance.now();inputAt=0;linear={x:0,y:0,z:0};wake();}}else if(data.type==='reset-motion'){gravity={x:0,y:-9.81,z:0};linear={x:0,y:0,z:0};inputAt=0;wake();}}catch(e){postMessage({type:'error',message:e.message});}};
postMessage({type:'ready'});
