import * as THREE from '../certification/vendor/three.module.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {MotionInput} from './motion.js';
const TAU=Math.PI*2;
export const sampleCoins=[{id:'map',chapter:'第 1 章',title:'地图上的那条线',mark:'I',asset:'map',sound:'map'},{id:'ledger',chapter:'第 2 章',title:'河流的账本',mark:'II',asset:'ledger',sound:'ledger'},{id:'wetland',chapter:'第 3 章',title:'水回来的地方',mark:'III',asset:'wetland',sound:'wetland'}];
const vecs=points=>points.map(([x,y])=>new THREE.Vector2(x,y));
export async function createScenes({root,sound,onFocus,onStatus,certificate}){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#17232c');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;root.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,60);scene.fog=new THREE.Fog('#17232c',12,28);const room=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight('#eaf2fa','#131e29',1.1));const key=new THREE.DirectionalLight('#ffefcd',3.1);key.position.set(-3,6,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=5;key.shadow.camera.bottom=-5;key.shadow.bias=-.001;scene.add(key);const fill=new THREE.DirectionalLight('#b4d6f3',1.3);fill.position.set(4,2,-3);scene.add(fill);
 const loader=new THREE.TextureLoader(),maps=await Promise.all(sampleCoins.map(c=>loader.loadAsync(`./assets/${c.asset}-face.png`)));for(const map of maps){map.colorSpace=THREE.SRGBColorSpace;map.repeat.set(.96,.96);map.offset.set(.02,.02);map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}
 const edgeMaterial=new THREE.MeshStandardMaterial({color:'#b69a60',metalness:.93,roughness:.31,envMapIntensity:1.25}),edgeGeometry=new THREE.LatheGeometry(vecs([[.249,-.045],[.258,-.037],[.262,-.022],[.262,.022],[.258,.037],[.249,.045]]),48),frontGeometry=new THREE.CircleGeometry(.249,64).rotateX(-Math.PI/2).translate(0,.045,0),backGeometry=new THREE.CircleGeometry(.249,48).rotateX(Math.PI/2).translate(0,-.045,0);
 function reverse(c){const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const ctx=canvas.getContext('2d');ctx.fillStyle='#9c8155';ctx.fillRect(0,0,512,512);ctx.strokeStyle='#d3b986';ctx.lineWidth=3;for(const r of [226,211,194]){ctx.beginPath();ctx.arc(256,256,r,0,TAU);ctx.stroke();}ctx.textAlign='center';ctx.fillStyle='#ead6aa';ctx.font='17px Georgia';ctx.fillText('THE SECOND LANGUAGE',256,164);ctx.font='68px Georgia';ctx.fillText(c.mark,256,294);ctx.font='19px Georgia';ctx.fillText('CHAPTER COLLECTION',256,355);const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t;}
 const backs=sampleCoins.map(reverse),materials=sampleCoins.map((c,i)=>({front:new THREE.MeshStandardMaterial({map:maps[i],bumpMap:maps[i],bumpScale:.008,metalness:.78,roughness:.43,envMapIntensity:.72}),back:new THREE.MeshStandardMaterial({map:backs[i],bumpMap:backs[i],bumpScale:.005,metalness:.88,roughness:.37})}));
 const stone=new THREE.MeshStandardMaterial({color:'#263943',roughness:.74}),brass=new THREE.MeshStandardMaterial({color:'#b3945b',metalness:.88,roughness:.32});
 let objects=new THREE.Group(),mode='plaza',slots=[],angle=0,velocity=0,focus=-1,drag=null,frame=0,lastFrame=0,worker=null,workerReady=false,pending=null,latest=null,previous=null,latestAt=0,ackedSequence=0,paused=false,frames=0,frameIntervals=[],count=32,statsByScene={},motionAllowed=false,motion=new MotionInput(),motionAngle=0;scene.add(objects);
 const dummy=new THREE.Object3D(),temporaryQ=new THREE.Quaternion(),previousQ=new THREE.Quaternion(),targetQ=new THREE.Quaternion(),previousPosition=new THREE.Vector3(),jarVisual=new THREE.Group();
 function certified(value){if(value?.chapter_id==='2026-10-09'){sampleCoins[2].certified=true;sampleCoins[2].attemptId=value.attempt_id;}}certified(certificate);
 function add(geometry,material,x=0,y=0,z=0,parent=objects){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);parent.add(m);return m;}
 function coin(parent,index,scale=1){const group=new THREE.Group();for(const [g,m]of [[edgeGeometry,edgeMaterial],[frontGeometry,materials[index].front],[backGeometry,materials[index].back]]){const mesh=add(g,m,0,0,0,group);mesh.castShadow=true;mesh.userData.coinIndex=index;}group.scale.setScalar(scale);parent.add(group);return group;}
 function clear(){statsByScene[mode]=stats();worker?.terminate();worker=null;workerReady=false;pending=latest=previous=null;ackedSequence=0;cancelAnimationFrame(frame);frame=0;scene.remove(objects);objects.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.geometry&&![edgeGeometry,frontGeometry,backGeometry].includes(o.geometry))o.geometry.dispose();if(o.material&&!Object.values(materials).some(m=>Object.values(m).includes(o.material))&&![stone,brass,edgeMaterial].includes(o.material))o.material.dispose();});objects=new THREE.Group();scene.add(objects);slots=[];frames=0;frameIntervals=[];sound.stop();}
 function stage(){const floor=add(new THREE.CircleGeometry(11,96),new THREE.MeshStandardMaterial({color:'#24333d',roughness:.7,metalness:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=.015;floor.receiveShadow=true;for(const r of [1.25,2.75,3.5,4.8]){const ring=add(new THREE.TorusGeometry(r,.009,5,120),brass,0,.024,0);ring.rotation.x=Math.PI/2;}for(let i=0;i<24;i++){const tick=add(new THREE.BoxGeometry(.014,.006,.28),brass,Math.sin(i*TAU/24)*3.5,.028,Math.cos(i*TAU/24)*3.5);tick.rotation.y=i*TAU/24;}}
 function plaza(){clear();mode='plaza';stage();camera.position.set(0,3.55,7.05);camera.lookAt(0,1.05,1.25);
  const pedestal=add(new THREE.LatheGeometry(vecs([[0,.06],[1.38,.06],[1.38,.15],[1.23,.20],[1.23,.32],[1.1,.38],[1.1,.62],[.98,.7],[.98,.81],[0,.81]]),80),stone);pedestal.receiveShadow=true;pedestal.castShadow=true;
  for(const [r,y]of [[1.32,.17],[1.16,.35],[1,.71]]){const ring=add(new THREE.TorusGeometry(r,.014,8,80),brass,0,y,0);ring.rotation.x=Math.PI/2;}
  const pool=add(new THREE.CircleGeometry(.94,80),new THREE.MeshPhysicalMaterial({color:'#184f5d',roughness:.16,metalness:.28,clearcoat:.8,clearcoatRoughness:.12}),0,.818,0);pool.rotation.x=-Math.PI/2;
  for(let i=0;i<7;i++){const h=.43+i*.035,stem=add(new THREE.CylinderGeometry(.012,.017,h,8),brass,Math.sin(i*2.3)*.39,.82+h/2,Math.cos(i*2.3)*.39);stem.rotation.z=(i-3)*.08;const reed=add(new THREE.CapsuleGeometry(.029,.16,4,8),brass,stem.position.x+h*Math.sin(stem.rotation.z),.88+h,stem.position.z);reed.rotation.z=stem.rotation.z;}
  for(let i=0;i<3;i++){const theta=i*TAU/3,g=new THREE.Group();g.position.set(Math.sin(theta)*2.85,.08,Math.cos(theta)*2.85);objects.add(g);const base=add(new THREE.LatheGeometry(vecs([[0,0],[.63,0],[.63,.10],[.54,.15],[.54,.27],[.46,.32],[0,.32]]),48),stone,0,0,0,g);base.castShadow=true;const band=add(new THREE.TorusGeometry(.54,.018,8,64),brass,0,.26,0,g);band.rotation.x=Math.PI/2;const c=coin(g,i,3.1);c.position.y=1.13;c.rotation.x=Math.PI/2-.16;slots.push({group:g,coin:c,theta});}
  angle=velocity=0;focus=-1;updatePlaza();resize();wake();}
 function updatePlaza(){for(const s of slots){const theta=s.theta+angle;s.group.position.set(Math.sin(theta)*2.85,.08,Math.cos(theta)*2.85);s.group.rotation.y=theta;}const index=((Math.round(-angle/(TAU/3))%3)+3)%3;if(index!==focus){focus=index;onFocus(sampleCoins[index]);}}
 function jar(amount){clear();mode='jar';count=amount;stage();camera.position.set(.45,3.30,9.7);camera.lookAt(0,2.24,0);jarVisual.clear();objects.add(jarVisual);jarVisual.position.y=2.35;
  const glass=new THREE.MeshPhysicalMaterial({color:'#eef9ff',roughness:.035,metalness:0,transmission:.96,thickness:.085,ior:1.46,envMapIntensity:1.3,attenuationColor:'#d3edf2',attenuationDistance:8,side:THREE.DoubleSide});const shell=add(new THREE.LatheGeometry(vecs([[0,-2.24],[1.48,-2.24],[1.58,-2.16],[1.59,-1.95],[1.59,1.85],[1.52,2.08],[1.48,2.14],[1.42,2.14],[1.45,1.84],[1.48,-1.97],[1.41,-2.08],[0,-2.08]]),80),glass,0,0,0,jarVisual);shell.renderOrder=2;
  const base=add(new THREE.CylinderGeometry(1.57,1.67,.16,64),stone,0,-2.20,0,jarVisual);base.receiveShadow=true;for(const [r,y]of [[1.58,-2.11],[1.51,2.12],[1.52,2.25]]){const rim=add(new THREE.TorusGeometry(r,.027,10,80),brass,0,y,0,jarVisual);rim.rotation.x=Math.PI/2;}
  add(new THREE.CylinderGeometry(1.52,1.52,.09,64),new THREE.MeshStandardMaterial({color:'#415660',metalness:.65,roughness:.31}),0,2.22,0,jarVisual);const cap=add(new THREE.LatheGeometry(vecs([[0,0],[.28,0],[.28,.06],[.17,.11],[.14,.2],[0,.23]]),48),brass,0,2.27,0,jarVisual);cap.castShadow=true;
  const meshes=materials.map((m,i)=>[addInstanced(edgeGeometry,edgeMaterial,i),addInstanced(frontGeometry,m.front,i),addInstanced(backGeometry,m.back,i)]);
  function addInstanced(g,m,i){const mesh=new THREE.InstancedMesh(g,m,Math.ceil((amount-i)/3));mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;objects.add(mesh);return mesh;}
  worker=new Worker(new URL('./physics-worker.js',import.meta.url),{type:'module'});const activeWorker=worker;worker.onmessage=({data})=>{if(worker!==activeWorker)return;if(data.type==='ready'){workerReady=true;worker.postMessage({type:'init',count});}else if(data.type==='error'){onStatus('运动模拟暂不可用');console.error(data.message);}else if(data.type==='snapshot'){previous=latest;latest=data;latestAt=performance.now();pending=meshes;if(!paused&&!document.hidden)for(const hit of data.hits)sound.collision(hit.kind,hit.strength);if(paused)worker.postMessage({type:'pause',value:true});else wake();}};worker.onerror=e=>{onStatus('运动模拟未能启动，请刷新');console.error(e.message);};onFocus(null);resize();wake();}
 function resize(){const w=root.clientWidth,h=root.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();wake();}
 function render(now){frame=0;if(paused||document.hidden)return;const dt=lastFrame?Math.min(.08,(now-lastFrame)/1000):1/60;if(lastFrame)frameIntervals.push(now-lastFrame);if(frameIntervals.length>120)frameIntervals.shift();lastFrame=now;let animate=false;
  if(mode==='plaza'){if(!drag){angle+=velocity*dt;velocity*=Math.exp(-dt*8);if(Math.abs(velocity)<.04){velocity=0;const target=Math.round(angle/(TAU/3))*TAU/3,delta=target-angle;if(Math.abs(delta)>.001){angle+=delta*(1-Math.exp(-dt*10));animate=true;}}else animate=true;}updatePlaza();}
  else if(latest&&pending){const alpha=Math.min(1,(now-latestAt)/(1000/60)),b=latest.transforms,a=previous?.transforms;for(let i=0;i<count;i++){const k=i*7;dummy.position.set(b[k],b[k+1],b[k+2]);temporaryQ.set(b[k+3],b[k+4],b[k+5],b[k+6]);if(a&&a.length===b.length){dummy.position.lerp(previousPosition.set(a[k],a[k+1],a[k+2]),1-alpha);previousQ.set(a[k+3],a[k+4],a[k+5],a[k+6]);temporaryQ.copy(previousQ).slerp(targetQ.set(b[k+3],b[k+4],b[k+5],b[k+6]),alpha);}dummy.quaternion.copy(temporaryQ);dummy.updateMatrix();for(const mesh of pending[i%3])mesh.setMatrixAt(Math.floor(i/3),dummy.matrix);}for(const list of pending)for(const mesh of list)mesh.instanceMatrix.needsUpdate=true;const p=latest.jar.position,q=latest.jar.rotation;jarVisual.position.set(p.x,p.y,p.z);jarVisual.quaternion.set(q.x,q.y,q.z,q.w);animate=alpha<1;}
  renderer.render(scene,camera);if(mode==='jar'&&latest&&ackedSequence!==latest.sequence){ackedSequence=latest.sequence;worker?.postMessage({type:'ack'});}frames++;onStatus(mode==='plaza'?'左右拖动 · 点币聆听':`${count} 枚示意币 · ${latest?.stats.sleeping===count?'静置':'自然堆积'}`);if(animate||drag)frame=requestAnimationFrame(render);
 }
 function wake(){if(!paused&&!document.hidden&&!frame)frame=requestAnimationFrame(render);}
 const canvas=renderer.domElement,ray=new THREE.Raycaster();canvas.addEventListener('pointerdown',e=>{if(!e.isPrimary)return;sound.prepare().catch(()=>{});drag={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,lastAt:performance.now(),moved:false};canvas.setPointerCapture(e.pointerId);velocity=0;wake();});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const now=performance.now(),dx=e.clientX-drag.lastX;drag.moved ||=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8;if(mode==='plaza'){angle+=dx*.008;velocity=dx*.008/Math.max(.008,(now-drag.lastAt)/1000);}else if(drag.moved&&now-drag.lastAt>30)worker?.postMessage({type:'shake',strength:Math.min(1.4,Math.abs(dx)/25+.3)});drag.lastX=e.clientX;drag.lastY=e.clientY;drag.lastAt=now;wake();});
 canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const tap=!drag.moved;drag=null;if(tap&&mode==='plaza'){const rect=canvas.getBoundingClientRect();ray.setFromCamera({x:(e.clientX-rect.left)/rect.width*2-1,y:-(e.clientY-rect.top)/rect.height*2+1},camera);const hit=ray.intersectObjects(slots.map(s=>s.coin),true)[0];if(hit)sound.theme(sampleCoins[hit.object.userData.coinIndex].sound).catch(e=>onStatus(e.message));}wake();});canvas.addEventListener('pointercancel',()=>{drag=null;velocity=0;wake();});
 function pause(value){if(value)statsByScene[mode]=stats();paused=value;worker?.postMessage({type:'pause',value});if(value){cancelAnimationFrame(frame);frame=0;sound.stop();drag=null;}else{lastFrame=0;wake();}}
 const observer=new ResizeObserver(resize);observer.observe(root);document.addEventListener('visibilitychange',()=>pause(document.hidden||root.closest('[hidden]')!==null));window.addEventListener('devicemotion',event=>{if(!motionAllowed||paused||mode!=='jar'||!workerReady)return;const angle=screen.orientation?.angle??window.orientation??0;if(angle!==motionAngle){motionAngle=angle;motion.reset();worker.postMessage({type:'reset-motion'});}if(motion.feed(event,angle,performance.now()))worker.postMessage({type:'input',gravity:motion.gravity,linear:motion.linear});else if(!motion.calibration)onStatus('保持手机静止，正在校准…');});
 function stats(){const sorted=[...frameIntervals].sort((a,b)=>a-b);return{mode,count:mode==='jar'?count:3,frames,rendererCalls:renderer.info.render.calls,renderFrameP95Ms:sorted[Math.floor(sorted.length*.95)]||0,...(mode==='jar'?(latest?.stats||{}):{focusedCoin:sampleCoins[focus]?.id}),motionAllowed,motion:motion.stats(),sound:sound.stats(),assetVersion:'coin-art-v2'};}
 plaza();
 return{show(kind,amount=count){pause(false);if(kind==='plaza')plaza();else jar(Number(amount));},pause,move(direction){angle+=direction*TAU/3;velocity=0;wake();},play(){return sound.theme(sampleCoins[focus]?.sound||'wetland');},shake(strength=1){worker?.postMessage({type:'shake',strength});},setCertificate(v){certified(v);if(mode==='plaza')onFocus(sampleCoins[focus]);},resetMotion(){motion.reset();worker?.postMessage({type:'reset-motion'});onStatus('保持手机静止，正在校准…');},async enableMotion(){if(!window.DeviceMotionEvent)throw Error('此设备不提供运动数据');const permission=typeof DeviceMotionEvent.requestPermission==='function'?DeviceMotionEvent.requestPermission():Promise.resolve('granted'),audio=sound.prepare();if(await permission!=='granted'){await audio;throw Error('未获得运动权限，仍可拖动或点按摇晃');}await audio;motion.reset();worker?.postMessage({type:'reset-motion'});motionAllowed=true;return true;},stats,allStats(){return{...statsByScene,[mode]:stats()};}};
}
