const root=new URL('./assets/',import.meta.url);
export function createCoinSound(){let context=null,master=null,enabled=true,currentTheme=null,themeGeneration=0,collisionCount=0,lastCollision=-1000;const buffers=new Map(),pending=new Map(),voices=new Set();
 async function prepare(){if(!context){context=new(window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.gain.value=.72;const limiter=context.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=10;limiter.ratio.value=12;limiter.attack.value=.003;limiter.release.value=.15;master.connect(limiter);limiter.connect(context.destination);}await context.resume();return context;}
 async function load(name){if(buffers.has(name))return buffers.get(name);if(!pending.has(name))pending.set(name,(async()=>{const r=await fetch(new URL(name,root));if(!r.ok)throw Error('声音暂未加载，请稍后再试');const b=await context.decodeAudioData(await r.arrayBuffer());buffers.set(name,b);pending.delete(name);return b;})().catch(e=>{pending.delete(name);throw e;}));return pending.get(name);}
 function source(buffer,volume,collision=false){const s=context.createBufferSource(),g=context.createGain();s.buffer=buffer;g.gain.value=volume;s.connect(g);g.connect(master);const record={source:s,gain:g,collision};voices.add(record);s.onended=()=>{voices.delete(record);s.disconnect();g.disconnect();if(currentTheme===record)currentTheme=null;};s.start();return record;}
 function stop(){themeGeneration++;for(const v of voices){try{v.source.stop();}catch{}}voices.clear();currentTheme=null;}
 async function theme(name){stop();const generation=themeGeneration;await prepare();const b=await load(`theme-${name}.mp3`);if(generation!==themeGeneration||!enabled)return;currentTheme=source(b,.72);}
 async function warmCollisions(){await prepare();await Promise.all(['glass-1.mp3','glass-2.mp3','glass-3.mp3','metal-1.mp3','metal-2.mp3','metal-3.mp3'].map(load));}
 function collision(kind,strength){if(!enabled||!context||context.state!=='running'||voices.size>=6||performance.now()-lastCollision<48)return;const family=kind==='glass'?'glass':'metal',variant=1+collisionCount%3,b=buffers.get(`${family}-${variant}.mp3`);if(!b)return;lastCollision=performance.now();collisionCount++;source(b,Math.min(.36,.055+strength*.27),true);}
 return{prepare,theme,collision,warmCollisions,stop,setEnabled(value){enabled=value;if(!value)stop();},stats(){return{state:context?.state||'unprepared',active:voices.size,buffers:buffers.size,collisionCount,themePlaying:Boolean(currentTheme),enabled};}};
}
