import {createCoinSound} from './sound.js?v=1';
const $=id=>document.getElementById(id),store={read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}},write(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}},remove(key){try{localStorage.removeItem(key);}catch{}}};
const prefix='tsl-certification-lab:',sound=createCoinSound();let paper=null,scene=null,scenePromise=null,currentTab='test',authenticated=false,requestGeneration=0;
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
async function api(path='',body){const r=await fetch('/api/certification-lab'+path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})}),value=await r.json();if(!r.ok){const error=new Error(value.error||'连接暂不可用');error.status=r.status;throw error;}return value;}
const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
function values(){const result={};for(const q of paper.items){if(q.type==='gap')result[q.id]=$('answerForm').elements[q.id]?.value||'';else result[q.id]=[...$('answerForm').querySelectorAll('input')].filter(e=>e.name===q.id&&e.checked).map(e=>e.value);if(q.type==='single')result[q.id]=result[q.id][0]||'';}return result;}
function renderPaper(value){paper=value;store.write(prefix+'active',paper.id);$('paper').hidden=false;$('paperHead').textContent=`${paper.chapter.number} · 八道理解题 · ${new Date(paper.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;const form=$('answerForm');form.replaceChildren();const answers=paper.result?Object.fromEntries(paper.result.details.map(d=>[d.id,d.answer])):store.read(prefix+'answers:'+paper.id,{});
 for(const [i,q]of paper.items.entries()){const field=make('fieldset',null,'card question');field.append(make('legend',`${i+1} / ${paper.items.length} · ${{single:'单选',multi:'多选',gap:'填空'}[q.type]}${q.choose?' · 选 '+q.choose+' 项':''}`),make('p',q.prompt));
  if(q.type==='gap'){const input=make('input');input.type='text';input.name=q.id;input.autocomplete='off';input.autocapitalize='none';input.spellcheck=false;input.maxLength=120;input.setAttribute('aria-label',`第 ${i+1} 题答案`);input.value=answers[q.id]||'';field.append(input);}
  else for(const o of q.options){const label=make('label',null,'option'),input=make('input');input.type=q.type==='multi'?'checkbox':'radio';input.name=q.id;input.value=o.id;input.checked=q.type==='multi'?(answers[q.id]||[]).includes(o.id):answers[q.id]===o.id;label.append(input,make('span',`${o.id}. ${o.text}`));field.append(label);}form.append(field);}
 form.querySelectorAll('input').forEach(e=>e.disabled=Boolean(paper.result));$('submitTest').hidden=Boolean(paper.result);$('result').hidden=!paper.result;$('newTest').textContent=paper.result?'再申请一份':'申请新测试';
 if(paper.result){$('result').replaceChildren(make('h2',paper.result.passed?'满分通过 · 测试认证':`${paper.result.score} 分 · 可以重测`),make('p',paper.result.passed?'这次已生成唯一测试记录；再次通过也沿用同一枚测试纪念币。':'以下是本次答卷解析。重测会独立随机组卷。'));for(const [i,d]of paper.result.details.entries()){const section=make('div',null,'result-item'+(d.ok?'':' wrong'));section.append(make('strong',`${i+1}. ${d.ok?'通过':'需要再理解'}`),make('p',d.explanation));$('result').append(section);}}
 }
$('answerForm').addEventListener('input',()=>{if(paper&&!paper.result)store.write(prefix+'answers:'+paper.id,values());});
async function history(){const index=await api();$('history').replaceChildren(make('h2','测试记录'));if(!index.attempts.length)$('history').append(make('p','第一份答卷完成后可在这里回看。','muted'));
 if(index.certificate){$('history').append(make('p','本章已有一份测试认证，重测不会增加纪念币。','muted'));store.write(prefix+'certificate',index.certificate);scene?.setCertificate(index.certificate);const view=make('button','查看测试纪念币');view.onclick=async()=>{await tab('plaza');scene?.move(1);};$('history').append(view);}
 for(const row of index.attempts){const button=make('button',`${new Date(row.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} · ${row.score===null?'未提交':row.score+' 分'}`);button.onclick=async()=>{try{renderPaper(await api('/attempts/'+row.id));$('paper').scrollIntoView({block:'start',behavior:'smooth'});}catch(e){toast(e.message);}};$('history').append(button);}
 }
$('newTest').onclick=async()=>{if(!authenticated)return;$('newTest').disabled=true;const generation=++requestGeneration;let id=store.read(prefix+'pending-new');id||=crypto.randomUUID();store.write(prefix+'pending-new',id);try{const value=await api('/attempts',{id});store.remove(prefix+'pending-new');if(generation===requestGeneration){renderPaper(value);await history();$('paper').scrollIntoView({block:'start',behavior:'smooth'});}}catch(e){toast(e.message);}finally{$('newTest').disabled=false;}};
$('submitTest').onclick=async()=>{if(!paper||paper.result)return;const who=paper.id,answers=values();if(paper.items.some(q=>!answers[q.id]||Array.isArray(answers[q.id])&&!answers[q.id].length)){toast('请完成全部八道题后提交');return;}$('submitTest').disabled=true;$('answerForm').querySelectorAll('input').forEach(e=>e.disabled=true);try{const value=await api('/attempts/'+who+'/submit',{answers});if(paper.id===who)renderPaper(value);await history();if(paper.id===who)$('result').scrollIntoView({block:'start',behavior:'smooth'});}catch(e){toast(e.message);if(e.status===409&&paper.id===who)renderPaper(await api('/attempts/'+who));}finally{$('submitTest').disabled=false;if(paper.id===who&&!paper.result)$('answerForm').querySelectorAll('input').forEach(e=>e.disabled=false);}};
async function ensureScene(){if(scene)return scene;scenePromise ||=import('./scenes.js?v=1').then(({createScenes})=>createScenes({root:$('scene'),sound,certificate:store.read(prefix+'certificate'),onFocus(coin){$('coinCaption').hidden=!coin;if(coin){$('coinCaption').querySelector('small').textContent=coin.chapter+(coin.certified?' · 测试认证纪念币':' · 主题样币');$('coinCaption').querySelector('h2').textContent=coin.title;}},onStatus(text){$('sceneStatus').textContent=text;}})).then(value=>{scene=value;window.__certificationLabStats=()=>scene.stats();return value;}).catch(error=>{scenePromise=null;throw error;});return scenePromise;}
async function tab(kind){currentTab=kind;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===kind)));$('testPanel').hidden=kind!=='test';$('scenePanel').hidden=kind==='test';$('plazaControls').hidden=kind!=='plaza';$('jarControls').hidden=kind!=='jar';window.scrollTo(0,0);sound.stop();if(kind==='test'){scene?.pause(true);return;}try{const view=await ensureScene();if(currentTab!==kind){view.pause(currentTab==='test');return;}view.show(kind,Number($('coinCount').value));}catch(e){$('sceneStatus').textContent='场景未能打开，请重新点按页签';toast('此浏览器未能启动三维场景');console.error(e);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('prevCoin').onclick=()=>scene?.move(-1);$('nextCoin').onclick=()=>scene?.move(1);$('playCoin').onclick=()=>scene?.play();$('coinCount').onchange=()=>scene?.show('jar',Number($('coinCount').value));$('shake').onclick=()=>{sound.prepare();scene?.shake(1);};$('strongShake').onclick=()=>{sound.prepare();scene?.shake(2.8);};$('sound').onchange=()=>sound.setEnabled($('sound').checked);$('motion').onclick=async()=>{try{await scene.enableMotion();$('motion').textContent='摇晃已启用';toast('可以轻轻摇晃手机');}catch(e){toast(e.message);}};
const ratingFields=[['understanding','题目理解难度'],['burden','十分钟负担'],['plaza','广场观赏效果'],['jar','玻璃罐观感'],['motion','摇晃自然度'],['sound','纪念声音听感']];
const draft=store.read(prefix+'feedback',{});for(const [id,label]of ratingFields){const row=make('label',null,'rating'),select=make('select');select.id='rating-'+id;select.setAttribute('aria-label',label);for(const [value,text]of [[0,'未评分'],[1,'1 · 不合适'],[2,'2 · 较差'],[3,'3 · 可用'],[4,'4 · 好'],[5,'5 · 很满意']]){const option=make('option',text);option.value=value;select.append(option);}select.value=draft[id]||0;row.append(make('span',label),select);$('ratings').append(row);select.onchange=saveFeedback;}$('feedbackNote').value=draft.note||'';$('feedbackNote').oninput=saveFeedback;
function feedback(){return Object.assign(Object.fromEntries(ratingFields.map(([id])=>[id,Number($('rating-'+id).value)])),{note:$('feedbackNote').value,tab:currentTab,paperId:paper?.id||null,scene:scene?.stats()||null,device:{width:innerWidth,height:innerHeight,userAgent:navigator.userAgent},preview:true});}
function saveFeedback(){store.write(prefix+'feedback',feedback());}
$('sendFeedback').onclick=async()=>{if(!authenticated){toast('请先在第二语言登录');return;}let payload=store.read(prefix+'pending-feedback');payload ||= {id:crypto.randomUUID(),feedback:feedback()};if(!payload.feedback.note&&!ratingFields.some(([id])=>payload.feedback[id])){toast('请先填写评分或感受');return;}store.write(prefix+'pending-feedback',payload);$('sendFeedback').disabled=true;try{await api('/feedback',payload);store.remove(prefix+'pending-feedback');toast('反馈已收到，本机记录继续保留');}catch(e){toast(e.message);}finally{$('sendFeedback').disabled=false;}};
$('exportFeedback').onclick=()=>{const blob=new Blob([JSON.stringify({feedback:feedback(),paper,certificate:store.read(prefix+'certificate')},null,2)],{type:'application/json'}),a=make('a');a.href=URL.createObjectURL(blob);a.download='second-language-certification-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
document.addEventListener('visibilitychange',()=>{if(document.hidden){saveFeedback();sound.stop();}});
window.addEventListener('pagehide',()=>{saveFeedback();sound.stop();scene?.pause(true);});
try{const session=await(await fetch('/api/session',{cache:'no-store'})).json();authenticated=session.authenticated;$('login').hidden=authenticated;$('newTest').disabled=!authenticated;if(authenticated){await history();const active=store.read(prefix+'active');if(active){try{renderPaper(await api('/attempts/'+active));}catch{store.remove(prefix+'active');}}}}catch(e){toast('连接暂不可用，请重新打开');}
