export function hash(value){let n=2166136261;for(const c of value){n^=c.charCodeAt(0);n=Math.imul(n,16777619);}return n>>>0;}
export function motif(seed){const n=hash(seed),notes=[0,2,4,7,9];return {frequency:180*2**(notes[n%5]/12+(n>>>5)%3)*(1+(n/0x100000000)*.013),decay:.28+((n>>>9)%20)/50,brightness:1.8+((n>>>15)%15)/10,detune:((n>>>20)%17)/100};}
export function coinSamples(seed,rate=24000){const p=motif(seed),out=new Float32Array(Math.round(rate*.8));for(let i=0;i<out.length;i++){const t=i/rate,attack=Math.min(1,t/.007),env=Math.exp(-t/p.decay)*Math.min(1,(out.length-1-i)/(rate*.06));out[i]=attack*env*(.50*Math.sin(t*2*Math.PI*p.frequency)+.22*Math.sin(t*2*Math.PI*p.frequency*p.brightness)*Math.exp(-t/.24)+.11*Math.sin(t*2*Math.PI*p.frequency*(3.9+p.detune))*Math.exp(-t/.1));}return out;}
export function createCoinSound(){let context=null,master=null,enabled=true;const buffers=new Map(),active=new Set(),last=new Map();
 function prepare(){if(!context){context=new(window.AudioContext||window.webkitAudioContext)();const limit=context.createDynamicsCompressor();limit.threshold.value=-12;limit.knee.value=6;limit.ratio.value=12;limit.attack.value=.003;limit.release.value=.12;master=context.createGain();master.gain.value=.6;master.connect(limit);limit.connect(context.destination);}return context.resume();}
 function play(seed,strength=1,collision=false){if(!enabled||!context||context.state!=='running'||active.size>=8)return;const now=performance.now();if(collision&&now-(last.get(seed)||-1000)<100)return;last.set(seed,now);if(last.size>600)last.delete(last.keys().next().value);
  let buffer=buffers.get(seed);if(!buffer){const samples=coinSamples(seed);buffer=context.createBuffer(1,samples.length,24000);buffer.copyToChannel(samples,0);if(buffers.size>=96)buffers.delete(buffers.keys().next().value);buffers.set(seed,buffer);}
  const source=context.createBufferSource(),gain=context.createGain();source.buffer=buffer;gain.gain.value=Math.min(.7,Math.max(.015,strength*(collision?.20:.48)));source.connect(gain);gain.connect(master);active.add(source);source.onended=()=>{active.delete(source);source.disconnect();gain.disconnect();};source.start();if(collision){gain.gain.setValueAtTime(gain.gain.value,context.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.17);source.stop(context.currentTime+.18);}
 }
 function stop(){for(const source of active){try{source.stop();}catch{}}active.clear();}
 return{prepare,play,stop,setEnabled(value){enabled=value;if(!value)stop();},stats(){return{active:active.size,buffers:buffers.size,state:context?.state||'unprepared'};}};
}
