import{readFile,writeFile,mkdir,copyFile}from'node:fs/promises';import{join}from'node:path';import{randomBytes}from'node:crypto';import{spawnSync}from'node:child_process';
import{assets,voices}from'./plan.mjs';
const dir=new URL('../../.cache/voice-lab/',import.meta.url);await mkdir(dir,{recursive:true});const action=process.argv[2],account='5410a3d3a18318f1da25db1dc5629e86';
const txt=await readFile(join(process.env.APPDATA,'xdg.config','.wrangler','config','default.toml'),'utf8'),oauth=txt.match(/^oauth_token\s*=\s*"([^"\r\n]+)"/m)?.[1];
async function cf(path,options={}){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/${path}`,{...options,headers:{authorization:`Bearer ${oauth}`,...options.headers},signal:AbortSignal.timeout(30000)});const raw=await r.text();let j;try{j=JSON.parse(raw);}catch{}if(!r.ok||j?.success===false)throw Error(JSON.stringify({status:r.status,errors:j?.errors,path}));return j;}
const stateFile=new URL('state.json',dir);let s;try{s=JSON.parse(await readFile(stateFile,'utf8'));}catch{}
if(action==='prepare'){
 if(s?.feedbackDatabaseId)throw Error('此试听已转为静态文件与 D1，禁止重新打开生成窗口。');
 if(!s){const j=await cf('storage/kv/namespaces',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'the-second-language-kokoro-voice-lab'})});s={account,name:'tsl-kokoro-voice-lab',project:'the-second-language-kokoro-lab',kvId:j.result.id,viewToken:randomBytes(24).toString('hex'),adminToken:randomBytes(32).toString('hex'),production:false,createdAt:new Date().toISOString()};await writeFile(stateFile,JSON.stringify(s));}
 const p=JSON.parse(await readFile('.cache/openrouter-provider.json','utf8'));await writeFile(new URL('secrets.json',dir),JSON.stringify({OPENROUTER_API_KEY:p.apiKey,VIEW_TOKEN:s.viewToken,ADMIN_TOKEN:s.adminToken}));
 await writeFile(new URL('wrangler.json',dir),JSON.stringify({name:s.name,account_id:account,main:'../../trials/voice-lab/worker.mjs',compatibility_date:'2026-10-04',workers_dev:false,preview_urls:false,observability:{enabled:false},vars:{APP_ORIGIN:`https://${s.project}.pages.dev`,GENERATION_DEADLINE:String(Date.now()+3*3600000),GENERATION_ENABLED:'true'},kv_namespaces:[{binding:'TRIAL_DATA',id:s.kvId}],ai:{binding:'AI'}}));await copyFile('web/icon.svg','trials/voice-lab/web/icon.svg');console.log(JSON.stringify({worker:s.name,project:s.project,kvId:s.kvId,voices:voices.length,assets:assets.length}));
}else{
 if(!s)throw Error('Prepare first');const origin=`https://${s.project}.pages.dev`;
 async function control(path,body,binary=false){const r=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers:{authorization:`Bearer ${s.adminToken}`,...(body===undefined?{}:{'content-type':binary?'audio/mpeg':'application/json'})},...(body===undefined?{}:{body:binary?body:JSON.stringify(body)}),signal:AbortSignal.timeout(300000)});if(!r.ok)throw Error(`${path}: ${r.status} ${await r.text()}`);return binary&&body===undefined?Buffer.from(await r.arrayBuffer()):r.json();}
 if(action==='pages'){
  let found=true;try{await cf(`pages/projects/${s.project}`);}catch(e){if(!String(e).includes('404'))throw e;found=false;}
  if(!found)await cf('pages/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:s.project,production_branch:'main',deployment_configs:{production:{services:{TRIAL_API:{service:s.name}}},preview:{services:{TRIAL_API:{service:s.name}}}}})});
  await mkdir(new URL('pages/',dir),{recursive:true});await writeFile(new URL('pages/wrangler.json',dir),JSON.stringify({name:s.project,compatibility_date:'2026-10-04',pages_build_output_dir:'../../../trials/voice-lab/web',services:[{binding:'TRIAL_API',service:s.name}]}));console.log(JSON.stringify({pagesReady:true}));
 }else if(action==='generate'||action==='verify'){
  const chosen=action==='verify'?assets.filter(a=>a.category!=='words'):assets;
  for(let i=0;i<chosen.length;i+=6){const ids=chosen.slice(i,i+6).map(a=>a.id),progress=await control('/api/progress?ids='+ids.join(',')),needed=progress.results.filter(p=>action==='generate'?!p.result:!p.validation).map(p=>p.id);if(!needed.length)continue;const r=await control('/api/'+action,{ids:needed});console.log(JSON.stringify({action,batch:i/6+1,of:Math.ceil(chosen.length/6),results:r.results}));if(r.results.some(p=>['waiting_credit','outcome_unknown','failed'].includes(p.state)))throw Error('Inspect outcomes before retrying');}
 }else if(action==='download'){
  await mkdir(new URL('raw/',dir),{recursive:true});const all=[];for(let i=0;i<assets.length;i+=6){const ids=assets.slice(i,i+6).map(a=>a.id),p=await control('/api/progress?ids='+ids.join(','));all.push(...p.results);await Promise.all(p.results.map(async row=>{if(row.result?.state!=='ready')throw Error('Not ready: '+row.id);await writeFile(new URL('raw/'+row.id+'.mp3',dir),await control('/api/raw-audio/'+row.id,undefined,true));}));console.log(JSON.stringify({downloaded:Math.min(i+6,assets.length),total:assets.length}));}await writeFile(new URL('returns.json',dir),JSON.stringify(all,null,2));
 }else if(action==='master'){
  await mkdir(new URL('mastered/',dir),{recursive:true});const stats=[];let n=0;for(const a of assets){const input=new URL('raw/'+a.id+'.mp3',dir),output=new URL('mastered/'+a.id+'.mp3',dir),args=['-hide_banner','-nostdin','-i',input.pathname.replace(/^\/([A-Z]:)/,'$1'),'-af','loudnorm=I=-20:TP=-2:LRA=11:print_format=json','-f','null','-'];const pass=spawnSync('.cache/tools/ffmpeg.exe',args,{encoding:'utf8',maxBuffer:3e6});if(pass.status!==0)throw Error('Decode failed: '+a.id);const m=JSON.parse(pass.stderr.slice(pass.stderr.lastIndexOf('{')));let filter,method;
   if(['input_i','input_tp','input_lra','input_thresh','target_offset'].every(k=>Number.isFinite(Number(m[k])))){filter=`loudnorm=I=-20:TP=-2:LRA=11:measured_I=${m.input_i}:measured_TP=${m.input_tp}:measured_LRA=${m.input_lra}:measured_thresh=${m.input_thresh}:offset=${m.target_offset}:linear=true`;method='two-pass-loudnorm';}
   else{const peak=Number(m.input_tp);filter=Number.isFinite(peak)?`volume=${-8-peak}dB`:'anull';method='short-clip-peak-fallback';}
   const done=spawnSync('.cache/tools/ffmpeg.exe',['-hide_banner','-nostdin','-y','-i',input.pathname.replace(/^\/([A-Z]:)/,'$1'),'-af',filter,'-ar','24000','-ac','1','-c:a','libmp3lame','-b:a','128k',output.pathname.replace(/^\/([A-Z]:)/,'$1')],{encoding:'utf8',maxBuffer:3e6});if(done.status!==0)throw Error('Master failed: '+a.id);stats.push({id:a.id,method,input:m});if(++n%12===0||n===assets.length)console.log(JSON.stringify({mastered:n,total:assets.length}));}await writeFile(new URL('mastering.json',dir),JSON.stringify(stats,null,2));
 }else if(action==='upload'){
  for(let i=0;i<assets.length;i+=6){await Promise.all(assets.slice(i,i+6).map(async a=>control('/api/upload-audio?id='+a.id,await readFile(new URL('mastered/'+a.id+'.mp3',dir)),true)));console.log(JSON.stringify({uploaded:Math.min(i+6,assets.length),total:assets.length}));}console.log(JSON.stringify(await control('/api/publish-manifest',{ready:assets.map(a=>a.id)})));
 }else if(action==='read'){
  const all=[];for(let i=0;i<assets.length;i+=6){all.push(...(await control('/api/progress?ids='+assets.slice(i,i+6).map(a=>a.id).join(','))).results);}await writeFile(new URL('returns.json',dir),JSON.stringify(all,null,2));console.log(JSON.stringify({results:all.length,ready:all.filter(r=>r.result?.state==='ready').length,verified:all.filter(r=>r.validation?.native).length,failures:all.filter(r=>r.result?.state!=='ready')}));
 }else if(action==='disable'){
  const file=new URL('wrangler.json',dir),j=JSON.parse(await readFile(file,'utf8'));j.vars.GENERATION_ENABLED='false';j.vars.GENERATION_DEADLINE='0';await writeFile(file,JSON.stringify(j));console.log(JSON.stringify({preparationDisabled:true}));
 }else if(action==='finalize'){
  const list=await cf(`storage/kv/namespaces/${s.kvId}/keys?prefix=feedback%2Fautomation-smoke-voice-lab-20261004%2F`);for(const k of list.result){if(!k.name.startsWith('feedback/automation-smoke-voice-lab-20261004/'))throw Error('Unexpected key');await cf(`storage/kv/namespaces/${s.kvId}/values/${encodeURIComponent(k.name)}`,{method:'DELETE'});}
  await cf(`workers/scripts/${s.name}/secrets/OPENROUTER_API_KEY`,{method:'DELETE'});const file=new URL('secrets.json',dir),j=JSON.parse(await readFile(file,'utf8'));delete j.OPENROUTER_API_KEY;await writeFile(file,JSON.stringify(j));console.log(JSON.stringify({syntheticFeedbackRemoved:list.result.length,generationSecretRemoved:true}));
 }else if(action==='feedback'){
  if(s.feedbackDatabaseId){const j=await control('/api/feedback-snapshot');await writeFile(new URL('feedback.json',dir),JSON.stringify(j.feedback,null,2));console.log(JSON.stringify({saved:j.feedback.length,storage:'D1'}));}else{
  const list=await cf(`storage/kv/namespaces/${s.kvId}/keys?prefix=feedback%2F`),all=[];for(const k of list.result){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/storage/kv/namespaces/${s.kvId}/values/${encodeURIComponent(k.name)}`,{headers:{authorization:`Bearer ${oauth}`}});if(!r.ok)throw Error('Feedback read failed');all.push(await r.json());}await writeFile(new URL('feedback.json',dir),JSON.stringify(all,null,2));console.log(JSON.stringify({saved:all.length}));
  }
 }else if(action==='link')console.log(origin+'/#access='+s.viewToken);
 else throw Error('Unknown action');
}
