import {costLabel} from './audio-plan.js?v=27';
import {chapterNumber} from './chapters.js?v=27';
export function createAudioConfig({api,getContext,toast}){
 const $=id=>document.getElementById(id),names={two:'第二部分例句',three:'第三部分逐句'};
 let mode=null,revision=0,quote=null,serial=0,busy=false;
 const post=(path,body,method='POST')=>api('/api/audio-config'+path,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 const selected=()=>Object.keys(names).filter(part=>$('audioPart-'+part).checked);
 const stateNames={pending:'等待处理',running:'正在生成',completed:'已完成',waiting_credit:'额度不足',needs_review:'需要核对'};
 function setBusy(value){busy=value;for(const id of ['audioSave','audioConfirm','audioConfirmBack','audioConfigBack','audioChapter','audioNextChoice','audioExistingChoice'])$(id).disabled=value;for(const part of Object.keys(names))$('audioPart-'+part).disabled=value;}
 async function refresh(){const r=await api('/api/audio-config');if(mode!=='next')revision=r.revision;const list=$('audioJobs');list.replaceChildren();for(const j of r.jobs||[]){const row=document.createElement('p');row.className='audio-job';row.textContent=`${j.chapter_id} · ${stateNames[j.state]||j.state}${j.total?' · '+j.cursor+'/'+j.total:''}${j.error?' · '+j.error:''}`;if(j.state==='waiting_credit'){const resume=document.createElement('button');resume.type='button';resume.className='bevel-button';resume.textContent='充值后继续';resume.onclick=async()=>{resume.disabled=true;try{await post('/resume',{id:j.id});await refresh();}catch(e){toast(e.message);resume.disabled=false;}};row.append(resume);}list.append(row);}return r;}
 function reset(){serial++;mode=null;quote=null;$('audioConfigChoices').hidden=false;$('audioConfigDetail').hidden=true;$('audioConfirmation').hidden=true;$('audioSave').hidden=false;$('audioConfigStatus').textContent='';}
 async function estimate(){const ticket=++serial;$('audioConfigStatus').textContent='正在核对费用…';try{const c=getContext().chapters.find(c=>c.id===$('audioChapter').value),r=await post('/estimate',mode==='next'?{mode}:{chapterId:c?.id,digest:c?.digest});if(ticket!==serial)return;for(const e of r.estimates)$('audioCost-'+e.part).textContent=e.cost?costLabel(e.cost):'待章节定稿';$('audioConfigStatus').textContent=mode==='next'?'按近期章节估算，实际按定稿内容与已有音频结算。':'已生成的相同音频不再收费。';}catch(e){if(ticket===serial){for(const p of Object.keys(names))$('audioCost-'+p).textContent='暂未核实';$('audioConfigStatus').textContent=e.message;}}}
 async function choose(nextMode){setBusy(true);try{const r=await refresh();revision=r.revision;mode=nextMode;quote=null;$('audioConfigChoices').hidden=true;$('audioConfigDetail').hidden=false;$('audioConfirmation').hidden=true;$('audioChapterRow').hidden=mode==='next';$('audioConfigBack').hidden=false;$('audioSave').textContent=mode==='next'?'保存下一章选配':'申请生成';$('audioModeTitle').textContent=mode==='next'?'下一章音频':'已有章节音频';for(const p of Object.keys(names))$('audioPart-'+p).checked=mode==='next'?r.next.includes(p):false;
 const select=$('audioChapter');select.replaceChildren();for(const c of [...getContext().chapters].reverse()){const o=document.createElement('option');o.value=c.id;o.textContent=`${c.studyDate||c.id} · ${chapterNumber(c)} · ${c.title}`;select.append(o);}if(getContext().current&&!getContext().current.kind)select.value=getContext().current.id;await estimate();
 }catch(e){toast(e.message);}finally{setBusy(false);}}
 $('audioNextChoice').onclick=()=>choose('next');$('audioExistingChoice').onclick=()=>choose('existing');$('audioConfigBack').onclick=()=>{reset();refresh().catch(()=>{});};$('audioChapter').onchange=()=>{quote=null;$('audioConfirmation').hidden=true;$('audioSave').hidden=false;estimate();};
 for(const p of Object.keys(names))$('audioPart-'+p).onchange=()=>{quote=null;$('audioConfirmation').hidden=true;$('audioSave').hidden=false;};
 $('audioSave').onclick=async()=>{setBusy(true);try{if(mode==='next'){const r=await post('/next',{parts:selected(),revision},'PUT');revision=r.revision;toast('下一章音频选配已保存');}else{const c=getContext().chapters.find(c=>c.id===$('audioChapter').value);quote=await post('/quote',{chapterId:c?.id,digest:c?.digest,parts:selected()});$('audioConfirmSummary').textContent=`${c.studyDate||c.id} · ${selected().map(p=>names[p]).join('、')}。本次预计 ${costLabel(quote.cost)}；相同音频自动复用。`;$('audioConfirmation').hidden=false;$('audioSave').hidden=true;}}catch(e){$('audioConfigStatus').textContent=e.message;}finally{setBusy(false);}};
 $('audioConfirm').onclick=async()=>{if(!quote)return;setBusy(true);try{await post('/confirm',{quoteId:quote.quoteId,confirmed:true});quote=null;reset();$('audioSave').hidden=false;await refresh();toast('已提交音频申请');}catch(e){$('audioConfigStatus').textContent=e.message;}finally{setBusy(false);}};
 $('audioConfirmBack').onclick=()=>{quote=null;$('audioConfirmation').hidden=true;$('audioSave').hidden=false;};
 $('settingsDialog').addEventListener('close',reset);
 let timer;document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(timer);});$('settingsButton').addEventListener('click',()=>{reset();refresh().catch(()=>{});clearInterval(timer);timer=setInterval(()=>{if(!$('settingsDialog').open||document.hidden){clearInterval(timer);return;}if(!$('audioConfigSection').hidden&&!busy)refresh().catch(()=>{});},10000);});
 return{reset};
}
