import {createChapterAnswerRecorder,clearChapterAudioDrafts,stopChapterCapture} from './chapter-test-recorder.js?v=30';
export function createChapterTestsUI({api:request,showDialog,toast,getContext}) {
 const policy='chapter-understanding-v2-oral7',api=(path,options={})=>request(path,{...options,headers:{...options.headers,'x-chapter-test-policy':policy}});
 const $=id=>document.getElementById(id),dialog=$('chapterTestsDialog'),body=$('chapterTestBody'),status=$('chapterTestStatus');
 const names={pending:'等待出题',running:'正在出题',ready:'可以作答',failed:'暂未完成',submitted:'已提交',reviewing:'正在核对回答',needs_audio:'部分回答需补录',review_failed:'核对暂未完成'};
 let recorders=[];function dispose(){for(const r of recorders)r.dispose();recorders=[];for(const a of body.querySelectorAll('audio'))a.pause();}
 const pauseOthers=keep=>{for(const a of dialog.querySelectorAll('audio'))if(a!==keep)a.pause();};
 let target=null,current=null,epoch=0,busy=false,requestId=null;
 const post=(path,value)=>api('/api/chapter-tests'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
 const draftKey=id=>'second-language-test-draft:'+id;
 const pendingKey=who=>'second-language-test-request:'+who.chapterId+':'+who.digest;
 function readDraft(id){try{return JSON.parse(localStorage.getItem(draftKey(id))||'{}');}catch{return {};}}
 function saveDraft(){if(['ready','needs_audio'].includes(current?.status)){try{localStorage.setItem(draftKey(current.id),JSON.stringify(current.answers));}catch{status.textContent='本机暂不能保存草稿，请勿关闭页面。';}}}
 function element(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
 function eligible(){const c=getContext();return c.authenticated&&!c.demo&&c.current&&!c.current.kind&&c.current.digest;}
 const disabledBefore=new WeakMap();
 function setBusy(value){busy=value;for(const node of dialog.querySelectorAll('button:not(.sheet-close),input')){if(value){if(!disabledBefore.has(node))disabledBefore.set(node,node.disabled);node.disabled=true;}else if(disabledBefore.has(node)){node.disabled=disabledBefore.get(node);disabledBefore.delete(node);}}}
 function controls(){const paper=['ready','needs_audio'].includes(current?.status),oral=current?.items.some(q=>q.type==='oral');$('chapterTestSubmit').hidden=!paper;$('chapterTestApply').hidden=!!current;$('chapterTestBack').hidden=!current;$('chapterTestFootnote').textContent=paper?(oral?'答案自动保存。口头回答只核对内容，不评价口语表现。':'答案自动保存在本机。提交后可查看解析。'):current?.status==='submitted'?'本次答卷已保存，可再次申请独立测试。':current?.status==='reviewing'?'答卷已保存，核对完成后在这里查看结果。':'20 道理解题 · 7 道听说 · 约 10 分钟';}
 async function library(){const token=++epoch;dispose();current=null;controls();body.replaceChildren();status.textContent='正在读取本章测试…';try{const data=await api('/api/chapter-tests?chapter='+encodeURIComponent(target.chapterId));if(token!==epoch||!dialog.open)return;status.textContent='每次新申请都会独立出题。';if(!data.tests.length)body.append(element('p','还没有测试。读完本章后，可以申请一份理解测试。','chapter-test-empty'));for(const test of data.tests){const button=element('button',undefined,'chapter-test-record');button.type='button';button.append(element('strong',names[test.status]||test.status),element('span',new Date(test.createdAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})+(test.digest!==target.digest?' · 原版章节':'')));button.onclick=()=>open(test.id);body.append(button);}}catch(e){if(token===epoch)status.textContent=e.message;}}
 function paper(){dispose();body.replaceChildren();controls();const result=current.result,who=current,editable=['ready','needs_audio'].includes(current.status);status.textContent=result?`本次得分 ${result.score} / 100 · 答对 ${result.right} / ${result.total} 题`:current.status==='needs_audio'?'请只补录未听清的回答，其他答案已经保存。':current.status==='reviewing'?'答卷已提交，正在核对口头回答。':'听说题请听题后回答；多选题需选出所有符合项。';const details=new Map((result?.details||[]).map(d=>[d.id,d]));
  if(current.status==='review_failed'){const retry=element('button','重新核对','bevel-button');retry.type='button';retry.onclick=async()=>{if(busy)return;setBusy(true);try{await post('/'+who.id+'/retry',{});await open(who.id);}catch(e){status.textContent=e.message;}finally{setBusy(false);}};body.append(retry);status.textContent='核对暂未完成，答卷与原声已保存。';}
  for(const [index,q] of current.items.entries()){const section=element('fieldset',undefined,'chapter-test-question');section.dataset.questionId=q.id;section.append(element('legend',`${index+1}. ${q.type==='oral'?'听说':q.type==='multi'?'多选':'单选'}`));const detail=details.get(q.id),answer=detail?.answer??current.answers[q.id];
   if(q.type==='oral'){const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=q.audioUrl;audio.setAttribute('aria-label','播放本题');audio.onplay=()=>{stopChapterCapture();pauseOthers(audio);};section.append(audio);if(detail)section.append(element('p',detail.prompt));const allow=editable&&(current.status==='ready'||current.unclear.includes(q.id));if(current.unclear.includes(q.id))section.append(element('p','这条回答没有听清，请重新录制。','practice-guidance'));const recorder=createChapterAnswerRecorder({testId:who.id,questionId:q.id,answerId:answer,editable:allow,api,pauseOthers,toast,onChanged(){if(current===who){delete current.answers[q.id];saveDraft();}},onSaved(id){if(current===who){current.answers[q.id]=id;saveDraft();}}});recorders.push(recorder);section.append(recorder.box);
   }else{section.append(element('p',q.prompt));for(const option of q.options){const label=element('label',undefined,'chapter-test-option'),input=document.createElement('input');input.type=q.type==='multi'?'checkbox':'radio';input.name=q.id;input.value=option.id;input.checked=Array.isArray(answer)?answer.includes(option.id):answer===option.id;input.disabled=!!result||!editable||current.status==='needs_audio';input.onchange=()=>{if(q.type==='single')current.answers[q.id]=option.id;else current.answers[q.id]=[...section.querySelectorAll('input:checked')].map(n=>n.value);saveDraft();};label.append(input,element('span',option.id+'. '+option.text));section.append(label);}}
   if(detail){const explanation=element('div',undefined,'chapter-test-explanation');explanation.append(element('strong',detail.ok?'回答正确':q.type==='oral'?'回答内容不符合本题要求':`正确选项：${detail.correct.join('、')}`),element('p',detail.explanation),element('blockquote',detail.quote));if(detail.oral)explanation.append(element('p','你的回答：'+detail.oral.transcript),element('p',detail.oral.reason));else for(const option of detail.options)explanation.append(element('p',option.id+' · '+option.reason));section.append(explanation);}body.append(section);}
 }
 async function open(id){const token=++epoch;saveDraft();dispose();current=null;controls();body.replaceChildren();status.textContent='正在打开测试…';try{const data=await api('/api/chapter-tests/'+id);if(token!==epoch||!dialog.open)return;const local=readDraft(id);current={...data,unclear:data.unclear||[],answers:{...local,...data.submittedAnswers}};if(data.status==='submitted'){clearChapterAudioDrafts(id).catch(()=>{});try{localStorage.removeItem(draftKey(id));}catch{}}if(data.status==='needs_audio')for(const q of current.unclear)if(local[q]&&local[q]!==data.submittedAnswers[q])current.answers[q]=local[q];if(['ready','submitted','reviewing','needs_audio','review_failed'].includes(data.status))paper();else{controls();status.textContent=names[data.status]||'等待处理';body.append(element('p',data.error||'后台收到申请后会出题，准备好后即可作答。','chapter-test-empty'));if(data.status==='failed'){const retry=element('button','重新处理','bevel-button');retry.type='button';retry.onclick=async()=>{if(busy)return;setBusy(true);try{await post('/'+id+'/retry',{});await open(id);}catch(e){status.textContent=e.message;}finally{setBusy(false);}};body.append(retry);}}}catch(e){if(token===epoch)status.textContent=e.message;}}
 $('chapterTestApply').onclick=async()=>{if(busy||!target)return;if(!navigator.onLine){toast('请联网后申请测试');return;}const who={...target};try{requestId ||= localStorage.getItem(pendingKey(who));}catch{}requestId ||= crypto.randomUUID();try{localStorage.setItem(pendingKey(who),requestId);}catch{}setBusy(true);status.textContent='正在提交申请…';try{const data=await post('',{id:requestId,...who,policy});try{localStorage.removeItem(pendingKey(who));}catch{}requestId=null;if(target?.chapterId===who.chapterId&&target?.digest===who.digest&&dialog.open)await open(data.id);}catch(e){status.textContent=e.message;}finally{setBusy(false);}};
 $('chapterTestSubmit').onclick=async()=>{if(busy||!['ready','needs_audio'].includes(current?.status))return;const data=current;if(recorders.some(r=>r.pending())){status.textContent='请结束录音并等回答保存后再提交。';return;}const incomplete=data.items.find(q=>q.type==='multi'?!data.answers[q.id]?.length:!data.answers[q.id]||data.status==='needs_audio'&&data.unclear.includes(q.id)&&data.answers[q.id]===data.submittedAnswers[q.id]);if(incomplete){status.textContent='请完成全部题目后再提交。';body.querySelector(`[data-question-id="${incomplete.id}"]`)?.scrollIntoView({block:'start',behavior:'smooth'});return;}if(!confirm('提交本次答卷？提交后不能修改已明确的答案，可重新申请测试。'))return;saveDraft();setBusy(true);status.textContent='正在保存答卷…';try{const response=await post('/'+data.id+'/submit',{answers:data.answers});data.result=response.result||null;data.status=response.status||'submitted';if(current?.id===data.id)paper();if(data.status==='submitted'){clearChapterAudioDrafts(data.id).catch(()=>{});try{localStorage.removeItem(draftKey(data.id));}catch{}}}catch(e){status.textContent=e.message+'；答案已保留，请重试提交。';}finally{setBusy(false);if(current)for(const input of body.querySelectorAll('input'))input.disabled=current.status!=='ready';}};
 $('chapterTestBack').onclick=()=>{saveDraft();library();};
 for(const id of ['chapterTestsButton','chapterTestsEndButton'])$(id).onclick=()=>{if(!eligible()){toast('请在已登录的正式章节中申请测试');return;}const c=getContext().current;target={chapterId:c.id,digest:c.digest};requestId=null;showDialog('chapterTestsDialog');library();};
 dialog.addEventListener('close',()=>{saveDraft();dispose();epoch++;});
 const poll=()=>{if(!dialog.open||busy||document.visibilityState!=='visible')return;if(current&&['pending','running','reviewing'].includes(current.status))open(current.id);};setInterval(poll,30000);document.addEventListener('visibilitychange',poll);window.addEventListener('online',poll);
 return {changed(){saveDraft();epoch++;if(dialog.open)dialog.close();target=null;current=null;requestId=null;$('chapterTestsButton').hidden=!eligible();},clear(){saveDraft();epoch++;dialog.close();current=null;target=null;$('chapterTestsButton').hidden=true;}};
}
