export function createChapterTestsUI({api,showDialog,toast,getContext}) {
 const $=id=>document.getElementById(id),dialog=$('chapterTestsDialog'),body=$('chapterTestBody'),status=$('chapterTestStatus');
 const names={pending:'等待出题',running:'正在出题',ready:'可以作答',failed:'暂未完成',submitted:'已提交'};
 let target=null,current=null,epoch=0,busy=false,requestId=null;
 const post=(path,value)=>api('/api/chapter-tests'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
 const draftKey=id=>'second-language-test-draft:'+id;
 const pendingKey=who=>'second-language-test-request:'+who.chapterId+':'+who.digest;
 function readDraft(id){try{return JSON.parse(localStorage.getItem(draftKey(id))||'{}');}catch{return {};}}
 function saveDraft(){if(current?.status==='ready'){try{localStorage.setItem(draftKey(current.id),JSON.stringify(current.answers));}catch{status.textContent='本机暂不能保存草稿，请勿关闭页面。';}}}
 function element(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
 function eligible(){const c=getContext();return c.authenticated&&!c.demo&&c.current&&!c.current.kind&&c.current.digest;}
 function setBusy(value){busy=value;for(const node of dialog.querySelectorAll('button:not(.sheet-close),input'))node.disabled=value;}
 function controls(){const paper=current?.status==='ready';$('chapterTestSubmit').hidden=!paper;$('chapterTestApply').hidden=!!current;$('chapterTestBack').hidden=!current;$('chapterTestFootnote').textContent=paper?'答案自动保存在本机。提交后可查看解析。':current?.status==='submitted'?'本次答卷已保存，可再次申请独立测试。':'20 道理解题 · 约 10 分钟';}
 async function library(){const token=++epoch;current=null;controls();body.replaceChildren();status.textContent='正在读取本章测试…';try{const data=await api('/api/chapter-tests?chapter='+encodeURIComponent(target.chapterId));if(token!==epoch||!dialog.open)return;status.textContent='每次新申请都会独立出题。';if(!data.tests.length)body.append(element('p','还没有测试。读完本章后，可以申请一份理解测试。','chapter-test-empty'));for(const test of data.tests){const button=element('button',undefined,'chapter-test-record');button.type='button';button.append(element('strong',names[test.status]||test.status),element('span',new Date(test.createdAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})+(test.digest!==target.digest?' · 原版章节':'')));button.onclick=()=>open(test.id);body.append(button);}}catch(e){if(token===epoch)status.textContent=e.message;}}
 function paper(){body.replaceChildren();controls();const result=current.result;status.textContent=result?`本次得分 ${result.score} / 100 · 答对 ${result.right} / ${result.total} 题`:'单选与多选题；多选题需选出所有符合项。';const details=new Map((result?.details||[]).map(d=>[d.id,d]));
  for(const [index,q] of current.items.entries()){const section=element('fieldset',undefined,'chapter-test-question');section.append(element('legend',`${index+1}. ${q.type==='multi'?'多选':'单选'}`),element('p',q.prompt));const detail=details.get(q.id),answer=detail?.answer??current.answers[q.id];for(const option of q.options){const label=element('label',undefined,'chapter-test-option'),input=document.createElement('input');input.type=q.type==='multi'?'checkbox':'radio';input.name=q.id;input.value=option.id;input.checked=Array.isArray(answer)?answer.includes(option.id):answer===option.id;input.disabled=!!result;input.onchange=()=>{if(q.type==='single')current.answers[q.id]=option.id;else current.answers[q.id]=[...section.querySelectorAll('input:checked')].map(n=>n.value);saveDraft();};label.append(input,element('span',option.id+'. '+option.text));section.append(label);}if(detail){const explanation=element('div',undefined,'chapter-test-explanation');explanation.append(element('strong',detail.ok?'回答正确':`正确选项：${detail.correct.join('、')}`),element('p',detail.explanation),element('blockquote',detail.quote));for(const option of detail.options)explanation.append(element('p',option.id+' · '+option.reason));section.append(explanation);}body.append(section);}
 }
 async function open(id){const token=++epoch;saveDraft();current=null;controls();body.replaceChildren();status.textContent='正在打开测试…';try{const data=await api('/api/chapter-tests/'+id);if(token!==epoch||!dialog.open)return;current={...data,answers:readDraft(id)};if(['ready','submitted'].includes(data.status))paper();else{controls();status.textContent=names[data.status]||'等待处理';body.append(element('p',data.error||'后台收到申请后会出题，准备好后即可作答。','chapter-test-empty'));if(data.status==='failed'){const retry=element('button','重新处理','bevel-button');retry.type='button';retry.onclick=async()=>{if(busy)return;setBusy(true);try{await post('/'+id+'/retry',{});await open(id);}catch(e){status.textContent=e.message;}finally{setBusy(false);}};body.append(retry);}}}catch(e){if(token===epoch)status.textContent=e.message;}}
 $('chapterTestApply').onclick=async()=>{if(busy||!target)return;if(!navigator.onLine){toast('请联网后申请测试');return;}const who={...target};try{requestId ||= localStorage.getItem(pendingKey(who));}catch{}requestId ||= crypto.randomUUID();try{localStorage.setItem(pendingKey(who),requestId);}catch{}setBusy(true);status.textContent='正在提交申请…';try{const data=await post('',{id:requestId,...who});try{localStorage.removeItem(pendingKey(who));}catch{}requestId=null;if(target?.chapterId===who.chapterId&&target?.digest===who.digest&&dialog.open)await open(data.id);}catch(e){status.textContent=e.message;}finally{setBusy(false);}};
 $('chapterTestSubmit').onclick=async()=>{if(busy||current?.status!=='ready')return;const data=current;const incomplete=data.items.find(q=>q.type==='multi'?!data.answers[q.id]?.length:!data.answers[q.id]);if(incomplete){status.textContent='请完成全部题目后再提交。';body.querySelector(`[name="${incomplete.id}"]`)?.closest('fieldset').scrollIntoView({block:'start',behavior:'smooth'});return;}if(!confirm('提交本次答卷并查看解析？提交后不能修改，可重新申请测试。'))return;saveDraft();setBusy(true);status.textContent='正在保存答卷…';try{const response=await post('/'+data.id+'/submit',{answers:data.answers});data.result=response.result;data.status='submitted';if(current?.id===data.id)paper();try{localStorage.removeItem(draftKey(data.id));}catch{}}catch(e){status.textContent=e.message+'；答案已保留，请重试提交。';}finally{setBusy(false);if(current?.status==='submitted')for(const input of body.querySelectorAll('input'))input.disabled=true;}};
 $('chapterTestBack').onclick=()=>{saveDraft();library();};
 for(const id of ['chapterTestsButton','chapterTestsEndButton'])$(id).onclick=()=>{if(!eligible()){toast('请在已登录的正式章节中申请测试');return;}const c=getContext().current;target={chapterId:c.id,digest:c.digest};requestId=null;showDialog('chapterTestsDialog');library();};
 dialog.addEventListener('close',()=>{saveDraft();epoch++;});
 const poll=()=>{if(!dialog.open||busy||document.visibilityState!=='visible')return;if(current&&['pending','running'].includes(current.status))open(current.id);};setInterval(poll,30000);document.addEventListener('visibilitychange',poll);window.addEventListener('online',poll);
 return {changed(){saveDraft();epoch++;if(dialog.open)dialog.close();target=null;current=null;requestId=null;$('chapterTestsButton').hidden=!eligible();},clear(){saveDraft();epoch++;dialog.close();current=null;target=null;$('chapterTestsButton').hidden=true;}};
}
