export function installNativeSpeech({toast}){
 const synth=window.speechSynthesis,mode=document.getElementById('speechMode'),stopButton=document.getElementById('speechStop'),voiceSelect=document.getElementById('speechVoice'),rate=document.getElementById('speechRate'),key='tsl-native-speech';let settings;try{settings=JSON.parse(localStorage.getItem(key)||'{}');}catch{settings={};}let current=null;
 settings=settings&&typeof settings==='object'?settings:{};
 if(!synth){mode.disabled=true;voiceSelect.disabled=true;return{stop(){}};}mode.value=['off','word','sentence'].includes(settings.mode)?settings.mode:'off';rate.value=['1','.85','.7'].includes(String(settings.rate))?settings.rate:'1';
 const save=()=>{settings={mode:mode.value,voice:voiceSelect.value,rate:rate.value};localStorage.setItem(key,JSON.stringify(settings));};
 function stop(){synth.cancel();stopButton.hidden=true;current=null;}
 function voices(){const old=voiceSelect.value||settings.voice,available=synth.getVoices().filter(v=>/^en[-_]/i.test(v.lang));voiceSelect.replaceChildren();const defaultVoice=document.createElement('option');defaultVoice.value='';defaultVoice.textContent='系统英语声音';voiceSelect.append(defaultVoice);for(const v of available){const o=document.createElement('option');o.value=v.voiceURI;o.textContent=`${v.name} · ${v.lang}`;voiceSelect.append(o);}voiceSelect.value=available.some(v=>v.voiceURI===old)?old:'';}
 voices();synth.addEventListener('voiceschanged',voices);mode.onchange=()=>{stop();save();};voiceSelect.onchange=rate.onchange=save;stopButton.onclick=stop;
 function say(text){if(!/[A-Za-z]/.test(text))return;stop();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=Number(rate.value);const available=synth.getVoices(),chosen=available.find(v=>v.voiceURI===voiceSelect.value)||available.find(v=>/^en-US$/i.test(v.lang));if(chosen)u.voice=chosen;u.onend=()=>{if(current===u){stopButton.hidden=true;current=null;}};u.onerror=()=>{if(current===u){stopButton.hidden=true;current=null;toast('系统朗读暂不可用，请再点一次或选择另一个英语声音');}};current=u;stopButton.hidden=false;synth.speak(u);}
 document.getElementById('article').addEventListener('click',event=>{if(mode.value==='off'||event.target.closest('button,a,code,.story-translation,.mono'))return;let text='';if(mode.value==='sentence'){const sentence=event.target.closest('.story-sentence,.example-pair p');if(sentence)text=sentence.textContent;else if(event.target.closest('.word-heading h1'))text=event.target.closest('h1').textContent;}else{const range=document.caretRangeFromPoint?.(event.clientX,event.clientY);let node=range?.startContainer,offset=range?.startOffset;if(!node){const pos=document.caretPositionFromPoint?.(event.clientX,event.clientY);node=pos?.offsetNode;offset=pos?.offset;}if(node?.nodeType===Node.TEXT_NODE&&document.getElementById('article').contains(node)){for(const m of node.textContent.matchAll(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g))if(offset>=m.index&&offset<=m.index+m[0].length){text=m[0];break;}}}if(!text&&event.target.closest('.word-heading h1'))text=event.target.closest('h1').textContent;if(text){event.preventDefault();event.stopImmediatePropagation();say(text);}},true);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});document.getElementById('practiceButton').addEventListener('click',stop,true);window.addEventListener('tsl-stop-speech',stop);return{stop};
}
