import {familyLabels} from './exam-spec.js?v=20';
export const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;};
export function drawVisual(v){if(!v)return null;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${v.width} ${v.height}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',v.title);svg.classList.add('listening-diagram');const shape=(tag,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,tag);for(const [k,val]of Object.entries(attrs))n.setAttribute(k,String(val));if(text)n.textContent=text;svg.append(n);};for(const r of v.routes)shape('polyline',{points:r.points.map(pt=>pt.join(',')).join(' '),fill:'none',stroke:'#8b9daf','stroke-width':6});for(const a of v.areas){shape('rect',{x:a.x,y:a.y,width:a.width,height:a.height,fill:'#edf3f9',stroke:'#6788a5','stroke-width':2});shape('text',{x:a.x+a.width/2,y:a.y+a.height/2,'text-anchor':'middle','dominant-baseline':'middle','font-size':16,fill:'#193e62'},a.label);}return svg;}
export function questionField(q,{setId,answers,changed,toast}){
 const field=el('fieldset','objective-item listening-item');field.id=`practice-${q.id}`;field.append(el('legend','',`${q.number}${q.answerCount?`–${q.number+q.answerCount-1}`:''}. ${q.prompt}`));
 if(q.family)field.append(el('p','practice-guidance',familyLabels[q.family]));if(q.instructions)field.append(el('p','practice-guidance',q.instructions));
 if(q.stimulus){field.append(el('div','objective-stimulus',q.stimulus.text));if(q.stimulus.headers){const table=el('table','practice-data-table'),head=el('tr');for(const h of q.stimulus.headers)head.append(el('th','',h));table.append(head);for(const row of q.stimulus.rows){const tr=el('tr');for(const cell of row)tr.append(el('td','',cell));table.append(tr);}const wrap=el('div','practice-data-wrap');wrap.append(table);field.append(wrap);}if(q.stimulus.steps){const steps=el('ol','objective-flow');for(const step of q.stimulus.steps)steps.append(el('li','',step));field.append(steps);}}
 if(q.type==='gap'){field.append(el('p','practice-guidance',q.numberOnly?'仅填写一个数字':`最多 ${q.maxWords} 个单词${q.allowNumber?'，可加一个数字':''}`));const input=el('input','text-input');Object.assign(input,{type:'text',maxLength:200,autocomplete:'off',autocapitalize:'none',spellcheck:false,value:answers[q.id]||''});input.setAttribute('aria-label',`第 ${q.number} 题答案`);input.oninput=()=>{answers[q.id]=input.value;changed();};field.append(input);}
 else for(const o of q.options){const label=el('label','listening-choice'),input=el('input');input.type=q.type==='multi'?'checkbox':'radio';input.name=`${setId}-${q.id}`;input.value=o.id;input.checked=q.type==='multi'?(answers[q.id]||[]).includes(o.id):answers[q.id]===o.id;input.onchange=()=>{if(q.type==='multi'){const selected=[...field.querySelectorAll('input:checked')].map(x=>x.value);if(selected.length>q.answerCount){input.checked=false;toast(`请选择 ${q.answerCount} 项`);return;}answers[q.id]=selected;}else answers[q.id]=o.id;changed();};label.append(input,el('span','',`${o.id}. ${o.text}`));field.append(label);}
 return field;
}
