import {el,questionField,drawVisual} from './objective.js?v=26';import {examSpec} from './exam-spec.js?v=26';
export function createReading({api,toast,openSource}){
 function render(set){const passages=set.reading?.passages||[];if(!passages.length)return null;const spec=examSpec('reading',set.reading.profile),card=el('section','practice-question reading-paper');card.id=`practice-${passages[0].id}`;card.append(el('div','section-band',`阅读 · ${spec.label} · 3 篇 / ${spec.total} 题`));
  const body=el('div','practice-question-body'),toolbar=el('div','listening-toolbar'),status=el('p','practice-guidance',`${spec.minutes} 分钟 · 可先阅读题面，开始后计时`),mode=el('select','text-input'),begin=el('button','primary-button','开始阅读'),submit=el('button','primary-button',`提交 ${spec.total} 题`),reveal=el('button','bevel-button','查看译文与解析'),feedback=el('div','practice-attempts');for(const [v,t]of [['test','测验 · 提交后查看解析'],['review','精读 · 可主动查看解析']]){const o=el('option','',t);o.value=v;mode.append(o);}toolbar.append(mode,begin,status);submit.disabled=true;reveal.disabled=true;body.append(toolbar);
  const key=`tsl-reading-${set.id}`;let stored;try{stored=JSON.parse(localStorage.getItem(key)||'null');}catch{}let state=stored?.id&&stored.answers&&Number.isInteger(stored.passage)?stored:{id:crypto.randomUUID(),mode:'test',answers:{},passage:0,positions:{},questionPositions:{},interrupted:false},started=false,submitted=false,deadline=0,timer=null;mode.value=state.mode;
  const article=el('div','reading-text'),questionPanel=el('div','reading-question-panel'),tabs=el('div','reading-tabs'),view=el('div','button-row'),textTab=el('button','bevel-button','文章'),questionTab=el('button','bevel-button','题目'),workspace=el('div','reading-workspace');view.append(textTab,questionTab);workspace.append(article,questionPanel);let shown='text';
  function local(){if(submitted)return;if(article.clientHeight)state.positions[state.passage]=article.scrollTop;if(questionPanel.clientHeight)state.questionPositions[state.passage]=questionPanel.scrollTop;localStorage.setItem(key,JSON.stringify(state));}
  async function save(){local();if(started&&!submitted)try{await api(`/api/practice/reading/sessions/${state.id}/progress`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({answers:state.answers,passage:state.passage,position:article.scrollTop,positions:state.positions,questionPositions:state.questionPositions,interrupted:state.interrupted})});}catch{toast('草稿已保存在本机，联网后继续');}}
  let pending, revealed=null;state.positions||={};state.questionPositions||={};state.passage=Math.max(0,Math.min(passages.length-1,state.passage));function show(i){clearTimeout(pending);state.passage=i;article.replaceChildren(el('h3','',passages[i].title));for(const p of passages[i].paragraphs){const section=el('section','reading-paragraph');section.id=`reading-${set.id}-${p.id}`;section.append(el('strong','',p.label),el('p','practice-prompt',p.text));const tr=revealed?.passages.find(x=>x.id===passages[i].id)?.paragraphs.find(x=>x.id===p.id)?.translation;if(tr)section.append(el('p','practice-answer',tr));article.append(section);}if(passages[i].visual)article.append(drawVisual(passages[i].visual));const links=el('div','practice-links');for(const link of passages[i].links){const b=el('button','bevel-button',link.chapterId+(link.useId?` · ${link.useId}`:''));b.onclick=()=>{document.getElementById('practiceDialog').close();openSource(link.chapterId,link.useId,set.sources.find(source=>source.id===link.chapterId)?.digest);};links.append(b);}links.hidden=!revealed;article.append(links);questionPanel.replaceChildren(el('p','practice-guidance',passages[i].instructions));for(const q of passages[i].questions)questionPanel.append(questionField(q,{setId:set.id,answers:state.answers,changed:local,toast}));if(revealed){const data=revealed.passages.find(x=>x.id===passages[i].id);for(const k of data.keys){const d=el('details','listening-result');d.append(el('summary','',`第 ${data.questions.find(q=>q.id===k.id).number} 题解析`),el('p','practice-answer',k.accepted.join(' / ')),el('p','practice-guidance',k.explanation));questionPanel.append(d);}}if(submitted)for(const input of questionPanel.querySelectorAll('input'))input.disabled=true;requestAnimationFrame(()=>{article.scrollTop=state.positions[i]||0;questionPanel.scrollTop=state.questionPositions[i]||0;});for(const [j,b]of [...tabs.children].entries())b.classList.toggle('selected',j===i);}
  function switchView(v){local();shown=v;workspace.dataset.view=v;textTab.classList.toggle('selected',v==='text');questionTab.classList.toggle('selected',v==='questions');}textTab.onclick=()=>switchView('text');questionTab.onclick=()=>switchView('questions');
  for(const [i,p]of passages.entries()){const b=el('button','bevel-button',`Passage ${i+1}`);b.onclick=()=>{local();save();show(i);};tabs.append(b);}body.append(tabs,view,workspace);show(state.passage);switchView(shown);
  article.onscroll=questionPanel.onscroll=()=>{clearTimeout(pending);pending=setTimeout(local,200);};
  function showAttempt(a){const box=el('div','practice-attempt');box.append(el('strong','',`${a.result.correct}/${a.result.total} · ${spec.label}${a.conditions.overtime?' · 超时':''}${a.conditions.interrupted?' · 有中断':''}${a.conditions.assisted?' · 已用辅助':''}`));for(const item of a.result.items){const details=el('details','listening-result');details.append(el('summary','',`${item.number} · ${item.score}/${item.total} · ${item.reason}`),el('p','practice-answer',`我的答案：${Array.isArray(item.raw)?item.raw.join(', '):item.raw||'未填写'}\n答案：${item.accepted.join(' / ')}`),el('p','practice-guidance',item.explanation));const evidence=el('button','bevel-button','定位原文证据');evidence.onclick=async()=>{try{const r=await api(`/api/practice/reading/sessions/${a.sessionId}/reveal`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});revealed=r;local();show(passages.findIndex(p=>p.id===item.passageId));switchView('text');requestAnimationFrame(()=>{const target=document.getElementById(`reading-${set.id}-${item.evidence[0]}`);article.scrollTop=target.offsetTop-article.offsetTop;target.classList.add('reading-evidence');});}catch(e){toast(e.message);}};details.append(evidence);box.append(details);}if(a.review){box.append(el('p','',a.review.summary));for(const p of a.review.priorities||[])box.append(el('p','practice-review-point',p));box.append(el('p','practice-guidance',a.review.nextStep));}feedback.append(box);}
  for(const a of set.reading.attempts||[])showAttempt(a);
  begin.onclick=async()=>{try{if(submitted){state={id:crypto.randomUUID(),mode:mode.value,answers:{},passage:0,positions:{},questionPositions:{},interrupted:false};submitted=false;revealed=null;feedback.replaceChildren();show(0);}state.mode=mode.value;const r=await api(`/api/practice/sets/${set.id}/reading/sessions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:state.id,mode:state.mode})});if(r.submitted){state.id=crypto.randomUUID();local();toast('旧尝试已提交，请再次点开始建立新尝试');return;}started=true;deadline=r.progress.deadline;begin.disabled=true;mode.disabled=true;submit.disabled=false;reveal.disabled=state.mode==='test';const tick=()=>{const seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));status.textContent=state.mode==='review'?'精读 · 不计测验时间':seconds?`剩余 ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:'时间已到，保留答案并记录超时，请提交';};clearInterval(timer);timer=setInterval(()=>{tick();save();},5000);tick();save();}catch(e){toast(e.message);}};
  reveal.onclick=async()=>{try{revealed=await api(`/api/practice/reading/sessions/${state.id}/reveal`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});local();show(state.passage);}catch(e){toast(e.message);}};
  submit.onclick=async()=>{if(!started)return;submit.disabled=true;await save();try{const r=await api(`/api/practice/reading/sessions/${state.id}/submit`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),answers:state.answers})});submitted=true;clearInterval(timer);feedback.replaceChildren();showAttempt({...r,sessionId:state.id});localStorage.removeItem(key);begin.disabled=false;begin.textContent='重新练习';mode.disabled=false;reveal.disabled=false;for(const input of questionPanel.querySelectorAll('input'))input.disabled=true;status.textContent='答卷已保存，Codex 将补充教学反馈。';}catch(e){toast(e.message);submit.disabled=false;}};
  const hide=()=>{if(document.hidden&&started&&!submitted){state.interrupted=true;save();}},close=()=>{clearInterval(timer);if(started&&!submitted){state.interrupted=true;save();}};document.addEventListener('visibilitychange',hide);document.getElementById('practiceDialog').addEventListener('close',close,{once:true});card.dispose=()=>{close();clearTimeout(pending);document.removeEventListener('visibilitychange',hide);document.getElementById('practiceDialog').removeEventListener('close',close);};card.focusQuestion=id=>{const i=passages.findIndex(p=>p.questions.some(q=>q.id===id));if(i<0)return false;local();show(i);switchView('questions');requestAnimationFrame(()=>document.getElementById(`practice-${id}`)?.scrollIntoView({block:'center'}));return true;};body.append(submit,reveal,feedback);card.append(body);return card;
 }
 return{render};
}
