import {describe,prose} from './text.js?v=24';
import {el} from './objective.js?v=24';
export function speakingRecorder({question,set,api,toast,pauseOthers,reload}){
 const draftDB=new Promise((resolve,reject)=>{const r=indexedDB.open('tsl-speaking-drafts',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 async function draft(operation,value){try{const db=await draftDB;return await new Promise((resolve,reject)=>{const t=db.transaction('drafts',operation==='get'?'readonly':'readwrite'),store=t.objectStore('drafts'),r=operation==='get'?store.get(question.id):operation==='put'?store.put(value,question.id):store.delete(question.id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}catch{return null;}}
 let disposed=false,busy=false,acquiring=false,captureVersion=0;
 async function clearSubmitted(id){try{const db=await draftDB;await new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite'),store=t.objectStore('drafts'),r=store.get(question.id);r.onsuccess=()=>{if(r.result?.id===id)store.delete(question.id);};t.oncomplete=resolve;t.onerror=()=>reject(t.error);});}catch{}}
 const box=el('section','speaking-recorder'),status=el('p','practice-guidance','录制原声，回听后提交；原文件保留，多模型采集后由 Codex 分析。'),start=el('button','primary-button','开始录音'),stop=el('button','bevel-button','结束录音'),submit=el('button','primary-button','提交原声'),file=el('input','text-input'),preview=el('audio','question-audio');file.type='file';file.accept='audio/*';file.setAttribute('aria-label','选择已有原声文件');preview.controls=true;preview.onplay=()=>pauseOthers(preview);stop.disabled=true;submit.disabled=true;let recorder=null,stream=null,blob=null,url=null,timer=null,startedAt=0,recordId=null;box.append(status,el('div','button-row'));box.lastChild.append(start,stop,submit);box.append(preview,el('p','practice-guidance','也可选择已有音频，单份最多十分钟 / 20 MiB。'),file);
 function ready(value,persist=true){recordId=recordId||crypto.randomUUID();if(persist)draft('put',{blob:value,id:recordId});if(disposed)return;if(url)URL.revokeObjectURL(url);blob=value;recordId=recordId||crypto.randomUUID();url=URL.createObjectURL(blob);preview.src=url;submit.disabled=false;status.textContent='原声已保留在当前页面，请先回听，再提交。';}
 function end(){captureVersion++;acquiring=false;if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());clearInterval(timer);start.disabled=busy;stop.disabled=true;file.disabled=busy;}
 start.onclick=async()=>{if(busy||recorder?.state==='recording')return;start.disabled=true;acquiring=true;const capture=++captureVersion;try{pauseOthers();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('当前浏览器不支持录音，可选择已有音频');start.disabled=false;acquiring=false;return;}const candidate=await navigator.mediaDevices.getUserMedia({audio:true});if(disposed||capture!==captureVersion){candidate.getTracks().forEach(t=>t.stop());return;}stream=candidate;acquiring=false;const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{recordId=null;const audio=new Blob(chunks,{type:recorder.mimeType||mime});if(audio.size)ready(audio);};recorder.onerror=()=>{end();toast('录音中断，请回听已有内容或重新录制');};recorder.start(1000);startedAt=Date.now();start.disabled=true;stop.disabled=false;submit.disabled=true;file.disabled=true;timer=setInterval(()=>{const seconds=Math.floor((Date.now()-startedAt)/1000);status.textContent=`正在录音 · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(seconds>=600)end();},500);}catch(e){if(capture===captureVersion){end();toast(e.message||'麦克风暂不可用');}}};stop.onclick=end;
 file.onchange=()=>{if(busy)return;const chosen=file.files[0];if(chosen){recordId=null;ready(chosen);}};
 submit.onclick=async()=>{if(!blob||busy)return;if(blob.size>20*1024*1024){toast('文件超过 20 MiB，请选择较短的原声');return;}busy=true;box.dataset.uploading='true';start.disabled=true;file.disabled=true;submit.disabled=true;const sentId=recordId;try{const type=blob.type?.split(';')[0]||(/\.m4a$/i.test(file.files[0]?.name||'')?'audio/mp4':'audio/wav');await api(`/api/practice/questions/${question.id}/speaking/audio?id=${recordId}`,{method:'PUT',headers:{'content-type':type},body:blob});await clearSubmitted(sentId);toast('原声已提交，转换、采集和反馈可在这里查看');await reload();}catch(e){toast(e.message);submit.disabled=false;}finally{busy=false;delete box.dataset.uploading;if(!disposed){start.disabled=false;file.disabled=false;}}};
 const names={preparing:'等待音频转换',collecting:'正在采集原声证据',waiting_credit:'等待 OpenRouter 充值',ready:'等待 Codex 分析',reviewing:'Codex 正在分析',reviewed:'已反馈',needs_attention:'需要核对采集问题'};
 for(const attempt of (set.speakingAttempts||[]).filter(a=>a.questionId===question.id)){const block=el('div','practice-attempt'),audio=el('audio','question-audio');audio.controls=true;audio.preload='none';audio.src=attempt.audioUrl;block.append(el('strong','',`${names[attempt.status]||attempt.status} · ${new Date(attempt.submittedAt).toLocaleString('zh-CN')}`),audio);audio.onplay=()=>pauseOthers(audio);if(attempt.hasFeedback){const b=el('button','bevel-button','查看原声反馈');b.onclick=async()=>{try{const result=await api(`/api/practice/speaking/attempts/${attempt.id}/feedback`),f=result.feedback;const content=el('div');content.append(el('p','',f.summary));for(const x of f.strengths||[])content.append(el('p','practice-review-point',`优势 · ${x}`));for(const x of f.priorities||[])content.append(el('p','practice-review-point',x));for(const x of f.findings||[])content.append(el('p','practice-review-point',typeof x==='string'?x:`${x.quote||''} · ${x.explanation||x.observation||''}`));if(f.analysisText){const answer=el('div','practice-answer');prose(answer,f.analysisText);content.append(answer);}if(f.dimensions){const d=el('details','listening-result');d.append(el('summary','', '四维分析'),el('p','practice-answer',describe(f.dimensions)));content.append(d);}content.append(el('p','practice-guidance',f.nextStep));block.append(content);b.disabled=true;}catch(e){toast(e.message);}};block.append(b);}box.append(block);}
 const hide=()=>{if(document.hidden&&recorder?.state==='recording')end();};document.addEventListener('visibilitychange',hide);box.pauseForNavigation=()=>{if(acquiring||recorder?.state==='recording')end();preview.pause();};box.dispose=()=>{disposed=true;end();preview.pause();for(const a of box.querySelectorAll('audio'))a.pause();if(url)URL.revokeObjectURL(url);document.removeEventListener('visibilitychange',hide);};draft('get').then(d=>{if(d?.blob&&!disposed&&!blob&&!acquiring&&recorder?.state!=='recording'){recordId=d.id;ready(d.blob,false);status.textContent='已恢复本机原声草稿，请回听或提交。';}});return box;
}
